[package]
name = "api"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "api"
path = "src/lib.rs"

[dependencies]
actix-web = "4"
actix-files = "0.6.0"
actix-session = { version = "0.7.2", features = ["cookie-session"] }
actix-web-httpauth = "0.8.0"
algorithms = { path = "../algorithms" }
dotenv = "0.15.0"
env_logger = "0.9.0"
geo = "0.22.1"
geojson = "0.24.0"
log = "0.4.17"
migration = { path = "../migration" }
model = { path = "../model" }
nominatim = { path = "../nominatim" }
reqwest = "0.11.14"
sea-orm = { version = "0.9.3", features = [
  "sqlx-mysql",
  "runtime-actix-native-tls",
  "macros",
] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0"
url = "2.3.1"
