[package]
name = "api"
version = "1.1.2"
edition = "2021"
publish = false

[lib]
name = "api"
path = "src/lib.rs"

[dependencies]
actix-web = "4"
actix-files = "0.6.0"
actix-session = { version = "0.7.2", features = ["cookie-session"] }
actix-web-httpauth = "0.8.0"
algorithms = { path = "../algorithms" }
geo = "0.24.0"
geojson = "0.24.0"
log = "0.4.17"
migration = { path = "../migration" }
model = { path = "../model" }
nominatim = { path = "../nominatim" }
reqwest = "0.11.14"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0.38"
url = "2.3.1"
