version: '2'
services:
  koji:
    image: ghcr.io/turtiesocks/koji:main
    container_name: koji
    command: "koji"
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql://user:password@host:3306/database_name
      START_LAT: 0
      START_LON: 0
      TILE_SERVER: "https://{s}.basemaps.cartocdn.com/rastertiles/voyager_labels_under/{z}/{x}/{y}{r}.png"
      PORT: 8080
    #mem_limit: 2048G
    #mem_reservation: 256M
    #cpus: 2 
    ports:
      - "9095:8080"
