version: '3.7'
services:
  rdm-tools-2:
    image: ghcr.io/turtiesocks/rdm-tools-2.0:main
    container_name: rdm-tools-2
    command: sh -c "yarn build && rdm-tools-2"
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql://user:password@host:3306/database_name
      START_LAT: 0
      START_LON: 0
      TILE_SERVER: "https://{s}.basemaps.cartocdn.com/rastertiles/voyager_labels_under/{z}/{x}/{y}{r}"
    ports:
      - "9095:8080"
