[package]
name = "koji-core"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "koji_core"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
macros = { workspace = true }
log = { workspace = true }
geojson = { workspace = true }
geo = { workspace = true }
geo-types = { workspace = true }
serde_with = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
