[package]
name = "geo_repair"
version = "1.0.0"
edition = "2021"
publish = false

[lib]
name = "geo_repair"
path = "src/lib.rs"

[dependencies]
geo-types = "0.7.9"
geo = "0.24.0"
byteorder = "1.3.4"
linked-hash-map = "0.5.2"
