[package]
name = "geo_repair"
version = "1.1.0"
edition = "2024"
publish = false

[lib]
name = "geo_repair"
path = "src/lib.rs"

[dependencies]
geo-types = "0.7.11"
geo = "0.26.0"
byteorder = "1.5.0"
linked-hash-map = "0.5.6"
