//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

use std::{collections::HashMap, time::Instant};

use koji_core::{EnsurePoints, KojiGeometryCollection};

use crate::query_args::{AdminReqParsed, ApiQueryArgs, FeatureRenderSpec};

use crate::{
    error::ModelError,
    utils::{
        json::JsonToModel,
        json_related_sort, parse_order,
    },
};

use super::{
    geofence_property::{Basic, FullPropertyModel},
    sea_orm_active_enums::Mode,
    *,
};

use koji_core::TrimPrecision;
use sea_orm::{DbBackend, Statement, UpdateResult, Value, entity::prelude::*};
use serde::{Deserialize, Serialize};
use serde_json::json;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "geofence")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    #[sea_orm(unique)]
    pub name: String,
    pub parent: Option<u32>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub mode: Mode,
    pub geometry: Json,
    pub geo_type: String,
    /// Dragonite area linkage (migration `m20260529_000003_dragonite_linkage`).
    /// `None` until the geofence is bound to a Dragonite area; publishing is
    /// gated on this being set (architecture §7/§9).
    pub dragonite_area_id: Option<u32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::Parent",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::project::Entity")]
    Project,
    #[sea_orm(has_many = "super::geofence_project::Entity")]
    GeofenceProject,
    #[sea_orm(has_many = "super::geofence_property::Entity")]
    GeofenceProperty,
    #[sea_orm(has_many = "super::route::Entity")]
    Route,
}

impl Related<project::Entity> for Entity {
    fn to() -> RelationDef {
        geofence_project::Relation::Project.def()
    }
    fn via() -> Option<RelationDef> {
        Some(geofence_project::Relation::Geofence.def().rev())
    }
}

impl Related<super::geofence_property::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeofenceProperty.def()
    }
}

impl Related<super::geofence_project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GeofenceProject.def()
    }
}

impl Related<super::route::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Route.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Serialize, Deserialize, FromQueryResult)]
pub struct GeofenceNoGeometry {
    pub id: u32,
    pub name: String,
    pub mode: Mode,
    pub geo_type: String,
    pub parent: Option<u32>,
    // pub created_at: DateTimeUtc,
    // pub updated_at: DateTimeUtc,
}

#[derive(Serialize, Deserialize, FromQueryResult)]
pub(crate) struct OnlyParent {
    pub parent: Option<u32>,
}

impl Model {
    #[allow(clippy::wrong_self_convention)]
    fn to_json(self) -> Json {
        json!(self)
    }

    #[allow(clippy::wrong_self_convention)]
    #[allow(clippy::result_large_err)]
    fn to_feature(
        self,
        property_map: &HashMap<u32, Vec<FullPropertyModel>>,
        name_map: &HashMap<u32, String>,
        spec: &FeatureRenderSpec,
    ) -> Result<Feature, ModelError> {
        let mut has_manual_parent = String::from("");

        let mut properties = if let Some(properties) = property_map.get(&self.id) {
            properties
                .iter()
                .map(|prop| {
                    if prop.name == "parent"
                        && let Some(val) = prop.value.as_ref()
                    {
                        has_manual_parent = val.clone();
                    }
                    prop.parse_db_value(&self)
                })
                .collect::<Vec<Basic>>()
        } else {
            vec![]
        };

        if spec.filters.excludes_name(&self.name) {
            return Err(ModelError::Geofence("Excluded name".to_string()));
        }
        let prop_names = properties
            .iter()
            .map(|prop| prop.name)
            .collect::<Vec<&str>>();
        if spec.filters.excludes_any_property(&prop_names) {
            return Err(ModelError::Geofence("Excluded property".to_string()));
        }

        let parent_name = if has_manual_parent.is_empty() {
            if let Some(parent_id) = self.parent {
                name_map.get(&parent_id).cloned()
            } else {
                None
            }
        } else {
            Some(has_manual_parent)
        };

        if spec.filters.excludes_parent(parent_name.as_deref()) {
            return Err(ModelError::Geofence("Excluded parent".to_string()));
        }

        if spec.output.adds_internal_props() {
            properties.push(Basic {
                name: "__id",
                value: serde_json::Value::from(self.id),
            });
            properties.push(Basic {
                name: "__name",
                value: serde_json::Value::from(self.name.to_string()),
            });
            properties.push(Basic {
                name: "__mode",
                value: serde_json::Value::from(self.mode.to_value()),
            });
            properties.push(Basic {
                name: "__parent",
                value: serde_json::Value::from(self.parent),
            });
        }
        if spec.properties.name {
            properties.push(Basic {
                name: "name",
                value: serde_json::Value::from(self.name),
            });
        }
        if spec.properties.id {
            properties.push(Basic {
                name: "id",
                value: serde_json::Value::from(self.id),
            });
        }
        if spec.properties.mode {
            properties.push(Basic {
                name: "mode",
                value: serde_json::Value::from(self.mode.to_value()),
            });
        }
        if spec.properties.group && parent_name.is_some() {
            properties.push(Basic {
                name: "group",
                value: serde_json::Value::from(parent_name.clone()),
            });
        }
        if spec.properties.parent {
            properties.push(Basic {
                name: "parent",
                value: serde_json::Value::from(parent_name.clone()),
            });
        }
        let geometry = serde_json::from_value::<geojson::Geometry>(self.geometry)?;

        let mut feature = Feature {
            geometry: Some(if spec.output.skip_precision_trim() {
                geometry
            } else {
                geometry.trim_precision(6)
            }),
            ..Feature::default()
        };
        for prop in properties.into_iter() {
            if prop.name.eq("parent") {
                feature.set_property(prop.name, parent_name.clone())
            } else {
                feature.set_property(prop.name, prop.value)
            }
        }

        if let Some(geofence_name) = feature.property("name")
            && let Some(geofence_name) = geofence_name.as_str()
        {
            feature.set_property("name", spec.name_modifier.apply(geofence_name));
        }

        if spec.output.tag_internal_id() {
            feature.id = Some(geojson::feature::Id::String(format!(
                "{}__{}__KOJI",
                self.id,
                self.mode.to_value()
            )));
        }
        Ok(feature)
    }

    fn get_related_projects(&self) -> Select<project::Entity> {
        self.find_related(project::Entity)
            .select_only()
            .column(project::Column::Id)
            .column(project::Column::Name)
    }

    fn get_related_routes(&self) -> Select<route::Entity> {
        self.find_related(route::Entity)
            .select_only()
            .column(route::Column::Id)
            .column(route::Column::Name)
    }

    fn get_related_properties(&self) -> Select<geofence_property::Entity> {
        self.find_related(geofence_property::Entity)
            .join(
                sea_orm::JoinType::Join,
                geofence_property::Relation::Property.def(),
            )
            .select_only()
            .column(geofence_property::Column::Id)
            .column(geofence_property::Column::PropertyId)
            .column(geofence_property::Column::GeofenceId)
            .column(geofence_property::Column::Value)
            .column(property::Column::Name)
            .column(property::Column::Category)
            .filter(geofence_property::Column::GeofenceId.eq(self.id))
    }
}

impl Model {
    /// Map this row to a `KojiGeometry` (the universal boundary type). The
    /// geometry JSON is parsed to geo-types and the `mode` column (now the
    /// canonical 4-value `Mode`) bridges directly to `koji_core::Mode` via the
    /// `enum_bridge!` `From` impl.
    #[allow(clippy::result_large_err)]
    pub fn to_koji_geometry(&self) -> Result<koji_core::KojiGeometry, ModelError> {
        let geometry = super::parse_geometry_json(&self.geometry)?;

        let meta = koji_core::KojiMeta {
            id: Some(self.id),
            name: Some(self.name.clone()),
            mode: self.mode.into(),
            parent_id: self.parent,
            ancestors: Vec::new(),
            extra: serde_json::Map::new(),
        };
        Ok(koji_core::KojiGeometry { geometry, meta })
    }
}


mod hierarchy;
mod list;
mod project_view;
mod reads;
mod writes;

// Preserve the public path `geofence::{Anchor, HierarchySpec, HierarchyArgError}`
// after the hierarchy types moved into `hierarchy.rs`.
pub use hierarchy::{Anchor, HierarchyArgError, HierarchySpec};

// Crate-internal descendants helpers consumed by the `descendants` read method
// in `reads.rs` (reached there via `use super::*`).
use hierarchy::{DescendantRow, ancestors_from_ancestry, build_descendants_sql};

pub struct Query;

#[cfg(test)]
mod to_koji_tests {
    // `Mode` here is the domain `koji_core::Mode` (what `KojiMeta`/`meta.mode`
    // use); the storage enum is aliased `DbMode` for the `Model` fixtures.
    use super::{Mode as DbMode, *};
    use koji_core::Mode;

    #[cfg(test)]
    fn test_model_defaults() -> Model {
        use chrono::Utc;
        Model {
            id: 0,
            name: String::new(),
            parent: None,
            created_at: Utc::now(),
            updated_at: Utc::now(),
            mode: DbMode::Unset,
            geometry: serde_json::json!(null),
            geo_type: String::new(),
            dragonite_area_id: None,
        }
    }

    #[test]
    fn model_maps_to_kojigeometry() {
        let model = Model {
            id: 42,
            name: "Boulder".to_string(),
            parent: Some(7),
            geometry: serde_json::json!({ "type": "Point", "coordinates": [1.0, 2.0] }),
            geo_type: "Point".to_string(),
            mode: DbMode::Fort,
            ..test_model_defaults()
        };

        let kg = model.to_koji_geometry().unwrap();
        assert!(matches!(kg.geometry, geo::Geometry::Point(_)));
        assert_eq!(kg.meta.id, Some(42));
        assert_eq!(kg.meta.name.as_deref(), Some("Boulder"));
        assert_eq!(kg.meta.parent_id, Some(7));
        assert_eq!(kg.meta.mode, Mode::Fort); // mode bridges Model.mode -> koji_core::Mode
    }

    /// `project_as_koji` returns the property-rich `to_feature` output as a
    /// `KojiGeometryCollection` (NOT the bare `to_koji_geometry`), byte-identical
    /// to what the v1 endpoint produced pre-S5b.1 (the same geojson
    /// `FeatureCollection` + Phase 1 `TryFrom` round-trip, now inside the DB
    /// method). These tests pin that exact transform over the per-row
    /// `Vec<Feature>` (the live `project_as_feature` half needs a DB and is
    /// exercised by integration).
    fn koji_collection_from_features(features: Vec<Feature>) -> KojiGeometryCollection {
        let fc = FeatureCollection {
            bbox: None,
            features: features
                .into_iter()
                .map(EnsurePoints::ensure_first_last)
                .collect(),
            foreign_members: None,
        };
        KojiGeometryCollection::try_from(fc).unwrap()
    }

    fn geofence_row_for_feature() -> Model {
        Model {
            id: 9,
            name: "Aurora".to_string(),
            parent: None,
            geometry: serde_json::json!({
                "type": "Polygon",
                "coordinates": [[[0.0, 0.0], [1.0, 0.0], [1.0, 1.0], [0.0, 0.0]]]
            }),
            geo_type: "Polygon".to_string(),
            mode: DbMode::Pokemon,
            ..test_model_defaults()
        }
    }

    /// The good case: a non-internal request that does NOT ask for `?mode`. The
    /// projected feature carries `id`/`name` (and any custom DB property) but no
    /// `mode` property, so nothing collides with a typed `KojiMeta` field and the
    /// `TryFrom` deserialize succeeds — `id`/`name` populate the typed fields.
    #[test]
    fn project_as_koji_transform_preserves_id_and_name_props() {
        let args = ApiQueryArgs {
            id: Some(true),
            name: Some(true),
            ..Default::default()
        };
        let feature = geofence_row_for_feature()
            .to_feature(
                &HashMap::new(),
                &HashMap::new(),
                &args.feature_render_spec(),
            )
            .unwrap();
        let coll = koji_collection_from_features(vec![feature]);

        assert_eq!(coll.items.len(), 1);
        let meta = &coll.items[0].meta;
        assert_eq!(meta.id, Some(9));
        assert_eq!(meta.name.as_deref(), Some("Aurora"));
    }

    /// When the request asks for `?mode` (non-internal), the projected feature
    /// carries `mode = "pokemon"` — the canonical 4-value string. `KojiMeta`'s
    /// `mode` deserialize maps it to `Mode::Pokemon` and the sibling `id`/`name`
    /// properties survive. `project_as_koji` reproduces the live endpoint exactly,
    /// so this pins the behavior.
    #[test]
    fn project_as_koji_mode_preserved_with_props() {
        let args = ApiQueryArgs {
            id: Some(true),
            name: Some(true),
            mode: Some(true), // emits the canonical 4-value `mode` string
            ..Default::default()
        };
        let feature = geofence_row_for_feature()
            .to_feature(
                &HashMap::new(),
                &HashMap::new(),
                &args.feature_render_spec(),
            )
            .unwrap();
        // Sanity: the feature carries the canonical 4-value string.
        assert_eq!(
            feature.property("mode").and_then(|v| v.as_str()),
            Some("pokemon")
        );

        let coll = koji_collection_from_features(vec![feature]);
        assert_eq!(coll.items.len(), 1);
        let meta = &coll.items[0].meta;
        // Canonical mode string maps to Mode; id/name preserved.
        assert_eq!(meta.mode, Mode::Pokemon);
        assert_eq!(meta.id, Some(9));
        assert_eq!(meta.name.as_deref(), Some("Aurora"));
    }
}
