[package]
name = "koji"
version = "0.3.5"
edition = "2021"

[workspace]
members = [
  ".",
  "algorithms",
  "api",
  "geo_repair",
  "migration",
  "model",
  "nominatim",
]

[dependencies]
api = { path = "api" }
env_logger = "0.9.0"
log = "0.4.17"
