[package]
name = "koji"
version = "1.3.4"
edition = "2021"

[workspace]
members = [
  ".",
  "algorithms",
  "api",
  "geo_repair",
  "migration",
  "model",
  "nominatim",
]

[dependencies]
api = { path = "api" }
dotenv = "0.15.0"
env_logger = "0.9.0"
log = "0.4.17"
