[package]
name = "koji"
version = "1.5.2"
edition = "2024"

[workspace]
members = [".", "algorithms", "api", "migration", "model", "nominatim"]

[dependencies]
api = { path = "api" }
dotenv = "0.15.0"
env_logger = "0.11.8"
log = "0.4.27"
mimalloc = "0.1.47"
