[package]
name    = "macros"
version = "1.5.4"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn         = { workspace = true }
quote       = { workspace = true }
proc-macro2 = { workspace = true }

[dev-dependencies]
serde             = { workspace = true }
serde_json        = { workspace = true }
serde_urlencoded  = { workspace = true }
log        = { workspace = true }
utoipa     = { workspace = true }
actix-web  = { workspace = true }
koji-core  = { workspace = true }
koji-db    = { workspace = true }
sea-orm    = { workspace = true }
