//! Boundary mapping between the sea-orm generated enums (`db::Category`,
//! `db::Mode`) and the pure domain enums in koji-core, generated by the
//! crate-local `enum_bridge!` macro. Keeps sea-orm confined to the db layer.
//!
//! The `Mode` bridge lives alongside its `DeriveActiveEnum` in
//! `sea_orm_active_enums.rs`. The legacy golbat-type bridge was removed in the
//! Phase 2 `Type` → `Mode` migration.

crate::enum_bridge!(
    crate::db::sea_orm_active_enums::Category,
    crate::category::Category,
    [Boolean, String, Number, Object, Array, Database, Color]
);
