//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

use std::collections::HashMap;

use super::*;

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "geofence_project")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub geofence_id: u32,
    pub project_id: u32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::geofence::Entity",
        from = "Column::GeofenceId",
        to = "super::geofence::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Geofence,
    #[sea_orm(
        belongs_to = "super::project::Entity",
        from = "Column::ProjectId",
        to = "super::project::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Project,
}

impl Related<super::geofence::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Geofence.def()
    }
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Project.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub struct Query;

impl Query {
    /// Reconcile the join rows for one fixed side against a desired id set on
    /// the other side: insert missing pairs, leave matches, delete stale rows.
    ///
    /// `fixed_col`/`fixed_val` pin the side that stays constant (e.g. the
    /// geofence); `other_col`/`other_of` address the side iterated from `ids`.
    /// `make` builds the `ActiveModel` for an inserted pair. Semantics are
    /// byte-identical to the two former mirror fns: the existing-map is keyed on
    /// the OTHER column, inserts pin fixed + loop value, and the final delete
    /// filters `fixed.eq(fixed_val)` AND `other.is_in(stale)`.
    async fn upsert_related<C: ConnectionTrait>(
        db: &C,
        ids: &[serde_json::Value],
        fixed_val: u32,
        fixed_col: Column,
        other_col: Column,
        other_of: impl Fn(&Model) -> u32,
        make: impl Fn(u32) -> ActiveModel,
    ) -> Result<(), DbErr> {
        let mut existing: HashMap<u32, bool> = Entity::find()
            .filter(fixed_col.eq(fixed_val))
            .all(db)
            .await?
            .into_iter()
            .map(|x| (other_of(&x), false))
            .collect();

        for id in ids.iter().filter_map(|id| id.as_u64()) {
            let id = id as u32;
            if existing.contains_key(&id) {
                existing.entry(id).and_modify(|f| *f = true);
            } else {
                make(id).insert(db).await?;
            }
        }

        let stale: Vec<u32> = existing
            .into_iter()
            .filter_map(|(id, exists)| if exists { None } else { Some(id) })
            .collect();
        if !stale.is_empty() {
            Entity::delete_many()
                .filter(fixed_col.eq(fixed_val))
                .filter(other_col.is_in(stale))
                .exec(db)
                .await?;
        }
        Ok(())
    }

    pub async fn upsert_related_by_geofence_id<C: ConnectionTrait>(
        db: &C,
        projects: &[serde_json::Value],
        geofence_id: u32,
    ) -> Result<(), DbErr> {
        Self::upsert_related(
            db,
            projects,
            geofence_id,
            Column::GeofenceId,
            Column::ProjectId,
            |x| x.project_id,
            |project_id| ActiveModel {
                geofence_id: Set(geofence_id),
                project_id: Set(project_id),
                ..Default::default()
            },
        )
        .await
    }

    /// The project ids a geofence is currently linked to (for event payloads:
    /// `geofence.updated`/`route.updated` carry `projectIds[]` resolved at
    /// emit time, not at the moment of the upsert, so a route's parent
    /// geofence resolves through this same helper).
    pub async fn project_ids_for_geofence(
        db: &DatabaseConnection,
        geofence_id: u32,
    ) -> Result<Vec<u32>, DbErr> {
        Ok(Entity::find()
            .filter(Column::GeofenceId.eq(geofence_id))
            .all(db)
            .await?
            .into_iter()
            .map(|m| m.project_id)
            .collect())
    }

    /// The geofence ids linked to a project (mirror of
    /// [`project_ids_for_geofence`](Self::project_ids_for_geofence); for
    /// membership-diff payloads — `project.geofences_changed` before/after
    /// maps are built from this, resolved fresh at diff time).
    pub async fn geofence_ids_for_project(
        db: &DatabaseConnection,
        project_id: u32,
    ) -> Result<Vec<u32>, DbErr> {
        Ok(Entity::find()
            .filter(Column::ProjectId.eq(project_id))
            .all(db)
            .await?
            .into_iter()
            .map(|m| m.geofence_id)
            .collect())
    }

    /// The distinct geofence ids linked to ANY of `project_ids` — the plural
    /// sibling of [`geofence_ids_for_project`](Self::geofence_ids_for_project),
    /// used by the `/v2/geofences?bbox&projects=` neighbour filter.
    pub async fn geofence_ids_for_projects(
        db: &DatabaseConnection,
        project_ids: &[u32],
    ) -> Result<Vec<u32>, DbErr> {
        let mut ids: Vec<u32> = Entity::find()
            .filter(Column::ProjectId.is_in(project_ids.iter().copied()))
            .all(db)
            .await?
            .into_iter()
            .map(|m| m.geofence_id)
            .collect();
        ids.sort_unstable();
        ids.dedup();
        Ok(ids)
    }

    pub async fn upsert_related_by_project_id(
        db: &DatabaseConnection,
        geofences: &[serde_json::Value],
        project_id: u32,
    ) -> Result<(), DbErr> {
        Self::upsert_related(
            db,
            geofences,
            project_id,
            Column::ProjectId,
            Column::GeofenceId,
            |x| x.geofence_id,
            |geofence_id| ActiveModel {
                geofence_id: Set(geofence_id),
                project_id: Set(project_id),
                ..Default::default()
            },
        )
        .await
    }
}
