//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

use std::collections::HashMap;

use super::*;

use sea_orm::{InsertResult, entity::prelude::*};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "geofence_project")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub geofence_id: u32,
    pub project_id: u32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::geofence::Entity",
        from = "Column::GeofenceId",
        to = "super::geofence::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Geofence,
    #[sea_orm(
        belongs_to = "super::project::Entity",
        from = "Column::ProjectId",
        to = "super::project::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Project,
}

impl Related<super::geofence::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Geofence.def()
    }
}

impl Related<super::project::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Project.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

pub struct Query;

impl Query {
    pub async fn get_all(db: &DatabaseConnection) -> Result<Vec<Model>, DbErr> {
        geofence_project::Entity::find().all(db).await
    }

    pub async fn create(db: &DatabaseConnection, new_model: Model) -> Result<Model, DbErr> {
        if let Some(existing) = geofence_project::Entity::find()
            .filter(geofence_project::Column::GeofenceId.eq(new_model.geofence_id))
            .filter(geofence_project::Column::ProjectId.eq(new_model.project_id))
            .one(db)
            .await?
        {
            let mut active_model: ActiveModel = existing.into();
            active_model.geofence_id = Set(new_model.geofence_id);
            active_model.project_id = Set(new_model.project_id);
            active_model.update(db).await
        } else {
            ActiveModel {
                geofence_id: Set(new_model.geofence_id),
                project_id: Set(new_model.project_id),
                ..Default::default()
            }
            .insert(db)
            .await
        }
    }

    pub async fn update(
        db: &DatabaseConnection,
        geofence_id: Option<u32>,
        project_id: Option<u32>,
    ) -> Result<Model, DbErr> {
        let old_model = geofence_project::Entity::find()
            .filter(geofence_project::Column::GeofenceId.eq(geofence_id))
            .filter(geofence_project::Column::ProjectId.eq(project_id))
            .one(db)
            .await?;
        if let Some(old_model) = old_model {
            let mut old_model: ActiveModel = old_model.into();
            if let Some(geofence_id) = geofence_id {
                old_model.geofence_id = Set(geofence_id);
            }
            if let Some(project_id) = project_id {
                old_model.project_id = Set(project_id);
            }
            old_model.update(db).await
        } else {
            Err(DbErr::Custom("Relation not found".to_string()))
        }
    }

    pub async fn update_by_id(
        db: &DatabaseConnection,
        id: u32,
        table: String,
        related_ids: Vec<u32>,
    ) -> Result<InsertResult<ActiveModel>, DbErr> {
        geofence_project::Entity::delete_many()
            .filter(
                if table == "geofence" {
                    geofence_project::Column::GeofenceId
                } else {
                    geofence_project::Column::ProjectId
                }
                .eq(id),
            )
            .exec(db)
            .await?;

        let new_models: Vec<ActiveModel> = related_ids
            .into_iter()
            .map(|related_id| ActiveModel {
                geofence_id: Set(if table == "geofence" { id } else { related_id }),
                project_id: Set(if table == "geofence" { related_id } else { id }),
                ..Default::default()
            })
            .collect();
        if !new_models.is_empty() {
            geofence_project::Entity::insert_many(new_models)
                .exec(db)
                .await
        } else {
            Ok(InsertResult { last_insert_id: 0 })
        }
    }

    pub async fn delete(
        db: &DatabaseConnection,
        geofence_id: Option<u32>,
        project_id: Option<u32>,
    ) -> Result<DeleteResult, DbErr> {
        if let (Some(geofence_id), Some(project_id)) = (geofence_id, project_id) {
            let existing = geofence_project::Entity::find()
                .filter(geofence_project::Column::GeofenceId.eq(geofence_id))
                .filter(geofence_project::Column::ProjectId.eq(project_id))
                .one(db)
                .await?;

            if let Some(existing) = existing {
                existing.delete(db).await
            } else {
                Err(DbErr::Custom("Relation not found".to_string()))
            }
        } else if let Some(geofence_id) = geofence_id {
            geofence_project::Entity::delete_many()
                .filter(geofence_project::Column::GeofenceId.eq(geofence_id))
                .exec(db)
                .await
        } else if let Some(project_id) = project_id {
            geofence_project::Entity::delete_many()
                .filter(geofence_project::Column::ProjectId.eq(project_id))
                .exec(db)
                .await
        } else {
            Err(DbErr::Custom(
                "Both geofence_id and project_id are missing".to_string(),
            ))
        }
    }

    /// Reconcile the join rows for one fixed side against a desired id set on
    /// the other side: insert missing pairs, leave matches, delete stale rows.
    ///
    /// `fixed_col`/`fixed_val` pin the side that stays constant (e.g. the
    /// geofence); `other_col`/`other_of` address the side iterated from `ids`.
    /// `make` builds the `ActiveModel` for an inserted pair. Semantics are
    /// byte-identical to the two former mirror fns: the existing-map is keyed on
    /// the OTHER column, inserts pin fixed + loop value, and the final delete
    /// filters `fixed.eq(fixed_val)` AND `other.is_in(stale)`.
    async fn upsert_related(
        db: &DatabaseConnection,
        ids: &[serde_json::Value],
        fixed_val: u32,
        fixed_col: Column,
        other_col: Column,
        other_of: impl Fn(&Model) -> u32,
        make: impl Fn(u32) -> ActiveModel,
    ) -> Result<(), DbErr> {
        let mut existing: HashMap<u32, bool> = Entity::find()
            .filter(fixed_col.eq(fixed_val))
            .all(db)
            .await?
            .into_iter()
            .map(|x| (other_of(&x), false))
            .collect();

        for id in ids.iter().filter_map(|id| id.as_u64()) {
            let id = id as u32;
            if existing.contains_key(&id) {
                existing.entry(id).and_modify(|f| *f = true);
            } else {
                make(id).insert(db).await?;
            }
        }

        let stale: Vec<u32> = existing
            .into_iter()
            .filter_map(|(id, exists)| if exists { None } else { Some(id) })
            .collect();
        if !stale.is_empty() {
            Entity::delete_many()
                .filter(fixed_col.eq(fixed_val))
                .filter(other_col.is_in(stale))
                .exec(db)
                .await?;
        }
        Ok(())
    }

    pub async fn upsert_related_by_geofence_id(
        db: &DatabaseConnection,
        projects: &[serde_json::Value],
        geofence_id: u32,
    ) -> Result<(), DbErr> {
        Self::upsert_related(
            db,
            projects,
            geofence_id,
            Column::GeofenceId,
            Column::ProjectId,
            |x| x.project_id,
            |project_id| ActiveModel {
                geofence_id: Set(geofence_id),
                project_id: Set(project_id),
                ..Default::default()
            },
        )
        .await
    }

    pub async fn upsert_related_by_project_id(
        db: &DatabaseConnection,
        geofences: &[serde_json::Value],
        project_id: u32,
    ) -> Result<(), DbErr> {
        Self::upsert_related(
            db,
            geofences,
            project_id,
            Column::ProjectId,
            Column::GeofenceId,
            |x| x.geofence_id,
            |geofence_id| ActiveModel {
                geofence_id: Set(geofence_id),
                project_id: Set(project_id),
                ..Default::default()
            },
        )
        .await
    }
}
