//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

use super::*;

use sea_orm::{
    DeleteResult, DeriveEntityModel, FromQueryResult, Order, QueryOrder, QuerySelect, Set,
    prelude::DateTimeUtc, sea_query::Expr,
};

mod enum_bridge;
pub mod geofence;
pub mod geofence_project;
pub mod geofence_property;
pub mod import;
pub mod plugin_config;
pub mod prelude;
pub mod project;
pub mod property;
pub mod route;
pub mod sea_orm_active_enums;
pub mod tile_server;
pub mod webhook;

#[derive(Debug, Serialize, FromQueryResult)]
pub(crate) struct NameId {
    id: u32,
    name: String,
}

#[derive(Debug, Serialize)]
pub struct PaginateResults<T> {
    results: T,
    total: u64,
    has_next: bool,
    has_prev: bool,
}


impl<T> PaginateResults<T> {
    /// Assemble a page from fetched results + sea-orm's totals. The
    /// has_prev/has_next formula lives here ONLY — it was previously
    /// copy-pasted across all six entities' paginate epilogues.
    pub(crate) fn from_page(results: T, total: sea_orm::ItemsAndPagesNumber, page: u64) -> Self {
        PaginateResults {
            results,
            total: total.number_of_items,
            has_prev: page > 0,
            has_next: page + 1 < total.number_of_pages,
        }
    }

    /// Decompose into `(results, total, has_next, has_prev)`. The fields are
    /// private (the struct's `Serialize` shape is the v1 wire contract); this
    /// accessor lets cross-crate v2 callers read the page data without exposing
    /// the fields or duplicating the query. Used by the `koji_resource!`-generated
    /// v2 list handlers.
    pub fn into_parts(self) -> (T, u64, bool, bool) {
        (self.results, self.total, self.has_next, self.has_prev)
    }
}

/// Parse a stored geometry `Json` column into a `geo::Geometry` — the shared
/// body of `route::Model::to_koji_geometry` and
/// `geofence::Model::to_koji_geometry` (previously duplicated verbatim).
#[allow(clippy::result_large_err)]
pub(crate) fn parse_geometry_json(
    geometry: &serde_json::Value,
) -> Result<geo::Geometry<koji_core::Precision>, crate::error::ModelError> {
    let gj = serde_json::from_value::<geojson::Geometry>(geometry.clone())
        .map_err(|e| crate::error::ModelError::Custom(format!("[GEOMETRY]: {e}")))?;
    geo::Geometry::try_from(&gj)
        .map_err(|e| crate::error::ModelError::Custom(format!("[GEOMETRY]: {e}")))
}

