//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

use crate::error::ModelError;

use super::*;

use sea_orm::{
    DeleteResult, DeriveEntityModel, FromQueryResult, Order, QueryOrder, QuerySelect,
    Set, prelude::DateTimeUtc, sea_query::Expr,
};

pub mod area;
mod enum_bridge;
pub mod geofence;
pub mod geofence_project;
pub mod geofence_property;
pub mod instance;
pub mod prelude;
pub mod project;
pub mod property;
pub mod route;
pub mod sea_orm_active_enums;
pub mod tile_server;


trait ToFeatureFromModel {
    fn to_feature(self, internal: bool) -> Result<Feature, ModelError>;
}

#[derive(Debug, Serialize, FromQueryResult)]
pub struct NameId {
    id: u32,
    name: String,
}

#[derive(FromQueryResult)]
pub struct NameType {
    pub name: String,
    pub instance_type: self::sea_orm_active_enums::Type,
}

#[derive(Debug, Clone, FromQueryResult, Serialize, Deserialize)]
pub struct NameTypeId {
    pub id: u32,
    pub name: String,
    pub mode: self::sea_orm_active_enums::Type,
    pub geo_type: Option<String>,
}

#[derive(Debug, FromQueryResult)]
pub struct AreaRef {
    pub id: u32,
    pub name: String,
    pub has_geofence: bool,
    pub has_pokemon: bool,
    pub has_quest: bool,
    pub has_fort: bool,
}


#[derive(Debug, Serialize)]
pub struct PaginateResults<T> {
    results: T,
    total: u64,
    has_next: bool,
    has_prev: bool,
}

impl Default for PaginateResults<()> {
    fn default() -> Self {
        PaginateResults {
            results: (),
            total: 0,
            has_next: false,
            has_prev: false,
        }
    }
}


#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(untagged)]
pub enum RdmInstanceArea {
    Leveling(koji_core::PointStruct),
    Single(koji_core::SingleStruct),
    Multi(koji_core::MultiStruct),
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct RdmInstance {
    pub area: RdmInstanceArea,
    pub radius: Option<u32>,
}


#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(untagged)]
pub enum InstanceParsing {
    Feature(Feature),
    Rdm(RdmInstance),
}

pub struct InsertsUpdates<T> {
    to_insert: Vec<T>,
    updates: usize,
    inserts: usize,
}

pub trait VecToJson {
    fn to_json(self) -> Vec<serde_json::Value>;
}
