//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

use crate::error::ModelError;

use super::*;

use sea_orm::{
    DeleteResult, DeriveEntityModel, FromQueryResult, Order, QueryOrder, QuerySelect, Set,
    prelude::DateTimeUtc, sea_query::Expr,
};

mod enum_bridge;
pub mod geofence;
pub mod geofence_project;
pub mod geofence_property;
pub mod plugin_config;
pub mod prelude;
pub mod project;
pub mod property;
pub mod route;
pub mod sea_orm_active_enums;
pub mod tile_server;

trait ToFeatureFromModel {
    fn to_feature(self, internal: bool) -> Result<Feature, ModelError>;
}

#[derive(Debug, Serialize, FromQueryResult)]
pub struct NameId {
    id: u32,
    name: String,
}

#[derive(FromQueryResult)]
pub struct NameType {
    pub name: String,
    pub instance_type: self::sea_orm_active_enums::Type,
}

#[derive(Debug, Clone, FromQueryResult, Serialize, Deserialize)]
pub struct NameTypeId {
    pub id: u32,
    pub name: String,
    pub mode: self::sea_orm_active_enums::Type,
    pub geo_type: Option<String>,
}

#[derive(Debug, Serialize)]
pub struct PaginateResults<T> {
    results: T,
    total: u64,
    has_next: bool,
    has_prev: bool,
}

impl Default for PaginateResults<()> {
    fn default() -> Self {
        PaginateResults {
            results: (),
            total: 0,
            has_next: false,
            has_prev: false,
        }
    }
}

pub struct InsertsUpdates {
    updates: usize,
    inserts: usize,
}

pub trait VecToJson {
    fn to_json(self) -> Vec<serde_json::Value>;
}
