//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

use crate::query_args::AdminReqParsed;

use crate::utils::{json::JsonToModel, json_related_sort, parse_order};

use super::*;
use sea_orm::entity::prelude::*;
use serde_json::json;
use std::str::FromStr;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "project")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub name: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::geofence::Entity")]
    Geofence,
}

impl Related<geofence::Entity> for Entity {
    fn to() -> RelationDef {
        geofence_project::Relation::Geofence.def()
    }
    fn via() -> Option<RelationDef> {
        Some(geofence_project::Relation::Project.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

/// Row shape for the batched project→geofence join in `paginate`: carries the
/// owning `project_id` alongside the same `geofence.id`/`geofence.name` the
/// per-row `get_related_geofences()` selected, so results can be grouped back
/// per project without an extra query per row.
#[derive(Debug, FromQueryResult)]
struct GeofenceForProject {
    project_id: u32,
    id: u32,
    name: String,
}

pub struct Query;

impl Query {
    /// Verbatim from `#[macros::crud_query]` (see `crates/macros/src/lib.rs`,
    /// `crud_query`) — hand-written here because `get_one_json` below needs to
    /// hydrate the `"geofences"` key the macro-generated version omits (see
    /// that fn's doc comment for the bug this fixes).
    pub async fn get_one<C: ConnectionTrait>(db: &C, id: String) -> Result<Model, ModelError> {
        let record = match id.parse::<u32>() {
            Ok(id) => Entity::find_by_id(id).one(db).await?,
            Err(_) => Entity::find().filter(Column::Name.eq(id)).one(db).await?,
        };
        if let Some(record) = record {
            Ok(record)
        } else {
            Err(ModelError::Geofence("Does not exist".to_string()))
        }
    }

    /// The project SHOW/EDIT read path (`GET /internal/projects/{id}` →
    /// `/api/v2/projects/{id}`, via the `koji_resource!`-generated `get_one`
    /// handler). Was `serde_json::json!(model)` off the bare
    /// `#[macros::crud_query]`-generated method — `project::Model` (this
    /// file, ~line 14) has no `geofences` field, so show/edit read
    /// `record.geofences` as `undefined` and rendered nothing, even though
    /// the LIST page (`paginate`, above) hand-builds a `"geofences"` array
    /// and its count showed correctly. Mirrors geofence's
    /// `get_one_json_with_related` (`crates/koji-db/src/db/geofence/reads.rs`):
    /// hydrate the id array the frontend's `ReferenceArrayInput`/
    /// `ReferenceArrayField source="geofences"` expect, via the same
    /// `geofence_project` junction `paginate` already joins through.
    pub async fn get_one_json(db: &DatabaseConnection, id: String) -> Result<Json, ModelError> {
        let record = Self::get_one(db, id).await?;
        let mut json = json!(record);
        json.as_object_mut().unwrap().insert(
            "geofences".to_string(),
            json!(geofence_project::Query::geofence_ids_for_project(db, record.id).await?),
        );
        Ok(json)
    }

    /// Verbatim from `#[macros::crud_query]`.
    pub async fn delete(db: &DatabaseConnection, id: u32) -> Result<DeleteResult, DbErr> {
        Entity::delete_by_id(id).exec(db).await
    }

    /// Verbatim from `#[macros::crud_query]`.
    pub async fn search(db: &DatabaseConnection, search: String) -> Result<Vec<Json>, DbErr> {
        Entity::find()
            .filter(Column::Name.like(format!("%{}%", search).as_str()))
            .into_json()
            .all(db)
            .await
    }

    pub async fn paginate(
        db: &DatabaseConnection,
        args: AdminReqParsed,
    ) -> Result<PaginateResults<Vec<Json>>, DbErr> {
        let paginator = project::Entity::find()
            .order_by(
                Column::from_str(&args.sort_by).unwrap_or(Column::Name),
                parse_order(&args.order),
            )
            .filter(Column::Name.like(format!("%{}%", args.q).as_str()))
            .paginate(db, args.per_page);
        let total = paginator.num_items_and_pages().await?;

        let results: Vec<Model> = paginator.fetch_page(args.page).await?;

        // Batched replacement for the former per-row N+1 (one
        // `get_related_geofences().into_json().all()` per project). One join over
        // the `geofence_project` junction, filtered by every project id on the
        // page, selecting the SAME `geofence.id` + `geofence.name` columns the
        // per-row `get_related_geofences()` selected; rows are then grouped back
        // per project. Two equivalence-preserving details:
        //   1. Element shape — `json!({ "id", "name" })` matches the old
        //      `select_only().column(Id).column(Name).into_json()` object (same
        //      keys, same insertion order id→name).
        //   2. Per-project order — the old `find_related` join carried no
        //      ORDER BY and MySQL returned each project's geofences in
        //      `geofence_project` insertion (PK) order (verified empirically
        //      against the pre-change code: a project linked geofence 666 then
        //      664 came back [666, 664], not id-sorted). Driving the batched
        //      read off the junction entity and ordering by its primary key
        //      reproduces that order deterministically for every project.
        let project_ids: Vec<u32> = results.iter().map(|p| p.id).collect();

        let mut geofence_map: std::collections::HashMap<u32, Vec<Json>> =
            std::collections::HashMap::new();
        if !project_ids.is_empty() {
            for row in geofence_project::Entity::find()
                .join(
                    sea_orm::JoinType::InnerJoin,
                    geofence_project::Relation::Geofence.def(),
                )
                .filter(geofence_project::Column::ProjectId.is_in(project_ids))
                .order_by(geofence_project::Column::Id, Order::Asc)
                .select_only()
                .column(geofence_project::Column::ProjectId)
                .column(geofence::Column::Id)
                .column(geofence::Column::Name)
                .into_model::<GeofenceForProject>()
                .all(db)
                .await?
            {
                geofence_map
                    .entry(row.project_id)
                    .or_default()
                    .push(json!({ "id": row.id, "name": row.name }));
            }
        }

        let mut results: Vec<Json> = results
            .into_iter()
            .map(|project| {
                json!({
                    "id": project.id,
                    "name": project.name,
                    "description": project.description,
                    // "created_at": fence.created_at,
                    // "updated_at": fence.updated_at,
                    "geofences": geofence_map.get(&project.id).cloned().unwrap_or_default(),
                })
            })
            .collect();

        if args.sort_by == "geofences" {
            json_related_sort(&mut results, &args.sort_by, &args.order);
        }

        Ok(PaginateResults::from_page(results, total, args.page))
    }

    pub async fn get_all(db: &DatabaseConnection) -> Result<Vec<Model>, DbErr> {
        project::Entity::find().all(db).await
    }

    pub async fn upsert_related_geofences(
        db: &DatabaseConnection,
        json: &serde_json::Value,
        geofence_id: u32,
    ) -> Result<(), DbErr> {
        if let Some(geofences) = json.get("geofences")
            && let Some(geofences) = geofences.as_array()
        {
            geofence_project::Query::upsert_related_by_project_id(db, geofences, geofence_id)
                .await?;
        };
        Ok(())
    }

    pub async fn upsert(db: &DatabaseConnection, id: u32, json: Json) -> Result<Model, ModelError> {
        let old_model: Option<Model> = Entity::find_by_id(id).one(db).await?;
        let mut new_model = json.to_project()?;

        let model = if let Some(old_model) = old_model {
            new_model.id = Set(old_model.id);
            new_model.update(db).await?
        } else {
            new_model.insert(db).await?
        };
        Query::upsert_related_geofences(db, &json, model.id).await?;

        Ok(model)
    }

    /// Same hydration as [`get_one_json`](Self::get_one_json) — this is the
    /// value handed straight back to the frontend after a create/PATCH
    /// (`koji_resource!`'s `create`/`update` handlers), so a save must also
    /// carry `"geofences"` or the just-saved record would render empty until
    /// a manual refetch.
    pub async fn upsert_json_return(
        db: &DatabaseConnection,
        id: u32,
        json: Json,
    ) -> Result<Json, ModelError> {
        let result = Query::upsert(db, id, json).await?;
        let mut out = json!(result);
        out.as_object_mut().unwrap().insert(
            "geofences".to_string(),
            json!(geofence_project::Query::geofence_ids_for_project(db, result.id).await?),
        );
        Ok(out)
    }
}
