//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

use crate::query_args::AdminReqParsed;

use crate::utils::{json::JsonToModel, json_related_sort, parse_order};

use super::*;
use futures::future;
use sea_orm::entity::prelude::*;
use serde_json::json;
use std::str::FromStr;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "project")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub name: String,
    pub api_endpoint: Option<String>,
    pub api_key: Option<String>,
    pub golbat: bool,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::geofence::Entity")]
    Geofence,
}

impl Related<geofence::Entity> for Entity {
    fn to() -> RelationDef {
        geofence_project::Relation::Geofence.def()
    }
    fn via() -> Option<RelationDef> {
        Some(geofence_project::Relation::Project.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl Model {
    fn get_related_geofences(&self) -> Select<geofence::Entity> {
        self.find_related(geofence::Entity)
            .select_only()
            .column(geofence::Column::Id)
            .column(geofence::Column::Name)
    }
}

/// Row shape for the batched project→geofence join in `paginate`: carries the
/// owning `project_id` alongside the same `geofence.id`/`geofence.name` the
/// per-row `get_related_geofences()` selected, so results can be grouped back
/// per project without an extra query per row.
#[derive(Debug, FromQueryResult)]
struct GeofenceForProject {
    project_id: u32,
    id: u32,
    name: String,
}

#[macros::crud_query]
pub struct Query;

impl Query {
    pub async fn get_one_json_with_related(
        db: &DatabaseConnection,
        id: String,
    ) -> Result<Json, ModelError> {
        match Query::get_one(db, id).await {
            Ok(record) => {
                let mut json = json!(record);
                let json = json.as_object_mut().unwrap();
                json.insert(
                    "geofences".to_string(),
                    json!(
                        record
                            .get_related_geofences()
                            .into_model::<NameId>()
                            .all(db)
                            .await?
                            .into_iter()
                            .map(|p| p.id)
                            .collect::<Vec<u32>>()
                    ),
                );
                Ok(json!(json))
            }
            Err(err) => Err(err),
        }
    }

    pub async fn paginate(
        db: &DatabaseConnection,
        args: AdminReqParsed,
    ) -> Result<PaginateResults<Vec<Json>>, DbErr> {
        let paginator = project::Entity::find()
            .order_by(
                Column::from_str(&args.sort_by).unwrap_or(Column::Name),
                parse_order(&args.order),
            )
            .filter(Column::Name.like(format!("%{}%", args.q).as_str()))
            .paginate(db, args.per_page);
        let total = paginator.num_items_and_pages().await?;

        let results: Vec<Model> = match paginator.fetch_page(args.page).await {
            Ok(results) => results,
            Err(err) => {
                log::error!("[project] Error paginating, {:?}", err);
                vec![]
            }
        };

        // Batched replacement for the former per-row N+1 (one
        // `get_related_geofences().into_json().all()` per project). One join over
        // the `geofence_project` junction, filtered by every project id on the
        // page, selecting the SAME `geofence.id` + `geofence.name` columns the
        // per-row `get_related_geofences()` selected; rows are then grouped back
        // per project. Two equivalence-preserving details:
        //   1. Element shape — `json!({ "id", "name" })` matches the old
        //      `select_only().column(Id).column(Name).into_json()` object (same
        //      keys, same insertion order id→name).
        //   2. Per-project order — the old `find_related` join carried no
        //      ORDER BY and MySQL returned each project's geofences in
        //      `geofence_project` insertion (PK) order (verified empirically
        //      against the pre-change code: a project linked geofence 666 then
        //      664 came back [666, 664], not id-sorted). Driving the batched
        //      read off the junction entity and ordering by its primary key
        //      reproduces that order deterministically for every project.
        let project_ids: Vec<u32> = results.iter().map(|p| p.id).collect();

        let mut geofence_map: std::collections::HashMap<u32, Vec<Json>> =
            std::collections::HashMap::new();
        if !project_ids.is_empty() {
            for row in geofence_project::Entity::find()
                .join(
                    sea_orm::JoinType::InnerJoin,
                    geofence_project::Relation::Geofence.def(),
                )
                .filter(geofence_project::Column::ProjectId.is_in(project_ids))
                .order_by(geofence_project::Column::Id, Order::Asc)
                .select_only()
                .column(geofence_project::Column::ProjectId)
                .column(geofence::Column::Id)
                .column(geofence::Column::Name)
                .into_model::<GeofenceForProject>()
                .all(db)
                .await?
            {
                geofence_map
                    .entry(row.project_id)
                    .or_default()
                    .push(json!({ "id": row.id, "name": row.name }));
            }
        }

        let mut results: Vec<Json> = results
            .into_iter()
            .map(|project| {
                json!({
                    "id": project.id,
                    "name": project.name,
                    "api_endpoint": project.api_endpoint,
                    "api_key": project.api_key,
                    "golbat": project.golbat,
                    "description": project.description,
                    // "created_at": fence.created_at,
                    // "updated_at": fence.updated_at,
                    "geofences": geofence_map.get(&project.id).cloned().unwrap_or_default(),
                })
            })
            .collect();

        if args.sort_by == "geofences" {
            json_related_sort(&mut results, &args.sort_by, args.order);
        }

        Ok(PaginateResults {
            results,
            total: total.number_of_items,
            has_prev: args.page > 0,
            has_next: args.page + 1 < total.number_of_pages,
        })
    }

    pub async fn get_all(db: &DatabaseConnection) -> Result<Vec<Model>, DbErr> {
        project::Entity::find().all(db).await
    }

    pub async fn get_json_cache(db: &DatabaseConnection) -> Result<Vec<sea_orm::JsonValue>, DbErr> {
        let results = Entity::find()
            .order_by(Column::Name, Order::Asc)
            .all(db)
            .await?;
        let geofences = future::try_join_all(results.iter().map(|result| {
            result
                .get_related_geofences()
                .into_model::<NameId>()
                .all(db)
        }))
        .await?;

        Ok(results
            .into_iter()
            .enumerate()
            .map(|(i, model)| {
                json!({
                    "id": model.id,
                    "name": model.name,
                    "geofences": geofences[i].iter().map(|r| r.id).collect::<Vec<u32>>()
                })
            })
            .collect())
    }

    pub async fn get_golbat_project(db: &DatabaseConnection) -> Result<Option<Model>, DbErr> {
        project::Entity::find()
            .filter(Column::Golbat.eq(true))
            .filter(Column::ApiEndpoint.is_not_null())
            .one(db)
            .await
    }

    // ponytail: project PATCH "geofences" bulk-assign emits no membership
    // events yet — wire when E9.1 builds the reverse-assign UI (snapshot
    // before/after around Query::upsert in a thin unsealed wrapper or macro
    // hook). koji-db must not write outbox itself, and the project PATCH
    // macro handler is sealed, so there is no clean hook here today.
    pub async fn upsert_related_geofences(
        db: &DatabaseConnection,
        json: &serde_json::Value,
        geofence_id: u32,
    ) -> Result<(), DbErr> {
        if let Some(geofences) = json.get("geofences")
            && let Some(geofences) = geofences.as_array()
        {
            geofence_project::Query::upsert_related_by_project_id(db, geofences, geofence_id)
                .await?;
        };
        Ok(())
    }

    pub async fn upsert(db: &DatabaseConnection, id: u32, json: Json) -> Result<Model, ModelError> {
        let old_model: Option<Model> = Entity::find_by_id(id).one(db).await?;
        let mut new_model = json.to_project()?;

        let model = if let Some(old_model) = old_model {
            new_model.id = Set(old_model.id);
            new_model.update(db).await?
        } else {
            new_model.insert(db).await?
        };
        Query::upsert_related_geofences(db, &json, model.id).await?;

        Ok(model)
    }

    pub async fn upsert_json_return(
        db: &DatabaseConnection,
        id: u32,
        json: Json,
    ) -> Result<Json, ModelError> {
        let result = Query::upsert(db, id, json).await?;
        Ok(json!(result))
    }
}
