//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

use super::*;
use koji_core::Precision;

use geojson::{self};
use sea_orm::{FromQueryResult, Order, QueryOrder, QuerySelect, entity::prelude::*};
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::str::FromStr;

use crate::query_args::AdminReqParsed;

use crate::{
    db::sea_orm_active_enums::Mode,
    error::ModelError,
    utils::{json::JsonToModel, parse_order},
};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "route")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub geofence_id: u32,
    pub name: String,
    pub description: Option<String>,
    pub mode: Mode,
    pub geometry: Json,
    #[sea_orm(column_type = "custom(\"MEDIUMINT UNSIGNED\")", nullable)]
    pub points: u32,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::geofence::Entity",
        from = "Column::GeofenceId",
        to = "super::geofence::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Geofence,
}

impl Related<super::geofence::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Geofence.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Debug, Serialize, Deserialize, FromQueryResult)]
pub struct RouteNoGeometry {
    pub id: u32,
    pub geofence_id: u32,
    pub name: String,
    pub description: Option<String>,
    pub mode: Mode,
    pub points: u32,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

impl Model {
    /// Map this route row to a `KojiGeometry` (the universal boundary type).
    /// Mirrors `geofence::Model::to_koji_geometry`: the geometry JSON is parsed
    /// to geo-types and the `mode` column (now the canonical 4-value `Mode`)
    /// bridges directly to `koji_core::Mode` via the `enum_bridge!` `From` impl.
    /// Routes have no `parent` hierarchy, so `parent_id`/`ancestors` stay at
    /// their defaults.
    #[allow(clippy::result_large_err)]
    pub fn to_koji_geometry(&self) -> Result<koji_core::KojiGeometry, ModelError> {
        let gj = serde_json::from_value::<geojson::Geometry>(self.geometry.clone())
            .map_err(|e| ModelError::Custom(format!("[GEOMETRY]: {e}")))?;
        let geometry = geo::Geometry::<Precision>::try_from(&gj)
            .map_err(|e| ModelError::Custom(format!("[GEOMETRY]: {e}")))?;

        // Route-only fields (no named slot in KojiMeta) ride in `extra`, which the
        // geojson serializer flattens into Feature `properties` — so the show page
        // (and any consumer) sees `geofence_id` + `description`, not just id/name/mode.
        let mut extra = serde_json::Map::new();
        extra.insert(
            "geofence_id".to_string(),
            serde_json::json!(self.geofence_id),
        );
        if let Some(description) = &self.description {
            extra.insert("description".to_string(), serde_json::json!(description));
        }

        let meta = koji_core::KojiMeta {
            id: Some(self.id),
            name: Some(self.name.clone()),
            mode: self.mode.into(),
            parent_id: None,
            ancestors: Vec::new(),
            extra,
        };
        Ok(koji_core::KojiGeometry { geometry, meta })
    }
}

#[macros::crud_query]
pub struct Query;

impl Query {
    pub async fn paginate(
        db: &DatabaseConnection,
        args: AdminReqParsed,
    ) -> Result<PaginateResults<Vec<Json>>, DbErr> {
        let column = Column::from_str(&args.sort_by).unwrap_or(Column::Name);

        let mut paginator = Entity::find()
            .select_only()
            .column(Column::Id)
            .column(Column::Name)
            .column(Column::Mode)
            .column(Column::Points)
            .column(Column::GeofenceId)
            .column(Column::Description)
            .column(Column::CreatedAt)
            .column(Column::UpdatedAt)
            .order_by(column, parse_order(&args.order))
            .filter(Column::Name.like(format!("%{}%", args.q).as_str()));

        if let Some(geofence_id) = args.geofenceid {
            paginator = paginator.filter(Column::GeofenceId.eq(geofence_id));
        }
        if let Some(mode) = args.mode {
            paginator = paginator.filter(Column::Mode.eq(mode));
        }
        if let Some(pointsmin) = args.pointsmin {
            if let Some(pointsmax) = args.pointsmax {
                paginator = paginator.filter(Column::Points.between(pointsmin, pointsmax));
            } else {
                paginator = paginator.filter(Column::Points.gt(pointsmin));
            }
        } else if let Some(pointsmax) = args.pointsmax {
            paginator = paginator.filter(Column::Points.lt(pointsmax));
        }

        let paginator = paginator
            .into_model::<RouteNoGeometry>()
            .paginate(db, args.per_page);
        let total = paginator.num_items_and_pages().await?;

        let results: Vec<Json> = paginator
            .fetch_page(args.page)
            .await?
            .into_iter()
            .map(|model| {
                json!({
                    "id": model.id,
                    "geofence_id": model.geofence_id,
                    "name": model.name,
                    "description": model.description,
                    "points": model.points,
                    "mode": model.mode,
                })
            })
            .collect();

        Ok(PaginateResults::from_page(results, total, args.page))
    }

    /// Fetch all route rows (ordered by name) and map each `Model` to a
    /// `KojiGeometry`, collecting into a `KojiGeometryCollection`. Returns
    /// `ModelError` to match `route::Model::to_koji_geometry`. The geojson
    /// property naming an `internal` flag would control is irrelevant for the
    /// self-describing `KojiMeta`, so it is not needed here.
    #[allow(clippy::result_large_err)]
    pub async fn as_koji_collection(
        conn: &DatabaseConnection,
    ) -> Result<koji_core::KojiGeometryCollection, ModelError> {
        let items = Entity::find()
            .order_by(Column::Name, Order::Asc)
            .all(conn)
            .await?;
        items
            .iter()
            .map(|item| item.to_koji_geometry())
            .collect::<Result<koji_core::KojiGeometryCollection, ModelError>>()
    }

    /// Fetch one route row by id and map it via `to_koji_geometry`. Returns
    /// `ModelError` to match the sibling Koji read methods.
    #[allow(clippy::result_large_err)]
    pub async fn get_one_koji(
        db: &DatabaseConnection,
        id: String,
    ) -> Result<koji_core::KojiGeometry, ModelError> {
        let record = Query::get_one(db, id).await?;
        record.to_koji_geometry()
    }

    pub async fn upsert<C: ConnectionTrait>(
        db: &C,
        id: u32,
        json: Json,
    ) -> Result<Model, ModelError> {
        let old_model = Entity::find_by_id(id).one(db).await?;
        let mut new_model = json.to_route()?;

        let model = if let Some(old_model) = old_model {
            new_model.id = Set(old_model.id);
            new_model.update(db).await?
        } else {
            new_model.insert(db).await?
        };
        Ok(model)
    }

    pub async fn upsert_json_return<C: ConnectionTrait>(
        db: &C,
        id: u32,
        json: Json,
    ) -> Result<Json, ModelError> {
        let result = Query::upsert(db, id, json).await?;
        Ok(json!(result))
    }
}

#[cfg(test)]
mod to_koji_tests {
    // `Mode` here is the domain `koji_core::Mode` (what `KojiMeta`/`meta.mode`
    // use); the storage enum is aliased `DbMode` for the `Model` fixtures and the
    // `route_mode` helper (which returns the sea-orm `Mode`).
    use super::{Mode as DbMode, *};
    use koji_core::{KojiGeometryCollection, Mode};

    #[cfg(test)]
    fn test_model_defaults() -> Model {
        use chrono::Utc;
                Model {
            id: 0,
            geofence_id: 0,
            name: String::new(),
            description: None,
            mode: DbMode::Unset,
            geometry: serde_json::json!(null),
            points: 0,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        }
    }

    #[test]
    fn route_model_to_koji_geometry_maps_mode_and_geometry() {
        let model = Model {
            id: 42,
            geofence_id: 7,
            name: "Patrol".to_string(),
            geometry: serde_json::json!({
                "type": "LineString",
                "coordinates": [[1.0, 2.0], [3.0, 4.0]]
            }),
            mode: DbMode::Fort,
            ..test_model_defaults()
        };

        let kg = model.to_koji_geometry().unwrap();
        assert!(matches!(kg.geometry, geo::Geometry::LineString(_)));
        assert_eq!(kg.meta.mode, Mode::Fort); // mode bridges Model.mode -> koji_core::Mode
        assert_eq!(kg.meta.name.as_deref(), Some("Patrol"));
        assert_eq!(kg.meta.id, Some(42));
        // Routes have no parent hierarchy.
        assert_eq!(kg.meta.parent_id, None);
        assert!(kg.meta.ancestors.is_empty());
    }

    fn route_row_for_feature() -> Model {
        Model {
            id: 3,
            geofence_id: 88,
            name: "patrol".to_string(),
            geometry: serde_json::json!({
                "type": "MultiPoint",
                "coordinates": [[1.0, 2.0], [3.0, 4.0]]
            }),
            mode: DbMode::Pokemon, // canonical 4-value mode
            ..test_model_defaults()
        }
    }

    /// S8 route-publish payload golden: the `RouteUpdated.route` `SingleVec` the
    /// publish handler emits. The producer is `get_one_koji(...)` wrapped in a
    /// one-item `KojiGeometryCollection`, run through the Phase 1B inherent
    /// `to_single_vec` (matrix-free). (`get_one_koji` only adds a DB fetch around
    /// `to_koji_geometry`, so testing the `Model` conversion pins the producer
    /// without a DB.) The golden `[[2,1],[4,3]]` was captured from the matrix
    /// oracle (`to_feature(false).to_single_vec()`) at the time of the S5d-1 swap,
    /// where the two paths were asserted byte-identical; it now stands as a
    /// permanent regression guard after the oracle dies.
    #[test]
    fn route_publish_single_vec_golden() {
        let model = route_row_for_feature();

        // Producer: Model -> to_koji_geometry -> one-item collection -> to_single_vec.
        let kg = model.to_koji_geometry().unwrap();
        let single_vec = KojiGeometryCollection::new(vec![kg]).to_single_vec();

        // The stored MultiPoint [[1,2],[3,4]] (lon,lat) becomes [lat, lon] points,
        // in order — the captured matrix golden.
        assert_eq!(
            single_vec,
            vec![[2.0, 1.0], [4.0, 3.0]],
            "route publish SingleVec diverged from the captured matrix golden"
        );
    }

}
