//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

use super::*;
use koji_core::Precision;

use chrono::Utc;
use geojson::{self, GeoJson};
use sea_orm::{FromQueryResult, Order, QueryOrder, QuerySelect, entity::prelude::*};
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::collections::HashMap;
use std::str::FromStr;

use koji_core::{KojiGeometry, KojiGeometryCollection};

use crate::query_args::AdminReqParsed;

use crate::{
    db::sea_orm_active_enums::Mode,
    error::ModelError,
    utils::{json::JsonToModel, parse_order},
};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "route")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: u32,
    pub geofence_id: u32,
    pub name: String,
    pub description: Option<String>,
    pub mode: Mode,
    pub geometry: Json,
    #[sea_orm(column_type = "custom(\"MEDIUMINT UNSIGNED\")", nullable)]
    pub points: u32,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::geofence::Entity",
        from = "Column::GeofenceId",
        to = "super::geofence::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Geofence,
}

impl Related<super::geofence::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Geofence.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Debug, Serialize, Deserialize, FromQueryResult)]
pub struct RouteNoGeometry {
    pub id: u32,
    pub geofence_id: u32,
    pub name: String,
    pub description: Option<String>,
    pub mode: Mode,
    pub points: u32,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

/// Route name: the legacy `__name`/`name` passthrough in `meta.extra` wins (so
/// existing producers keep working), else the typed `meta.name`.
fn route_name(item: &KojiGeometry) -> Option<String> {
    item.meta
        .extra
        .get("__name")
        .or_else(|| item.meta.extra.get("name"))
        .and_then(|v| v.as_str())
        .map(str::to_string)
        .or_else(|| item.meta.name.clone())
}

/// Route mode as the storage [`Mode`]: prefer any original `__mode`/`mode`
/// string carried in `meta.extra` (a legacy 12-value OR a canonical 4-value
/// string — both collapse correctly via `Mode::from_legacy`), else fall back to
/// the typed `meta.mode`. The column is now the 4-value `Mode`, so this is a
/// direct bridge — no representative-`Type` dance.
fn route_mode(item: &KojiGeometry) -> Mode {
    let core_mode = item
        .meta
        .extra
        .get("__mode")
        .or_else(|| item.meta.extra.get("mode"))
        .and_then(|v| v.as_str())
        .map(koji_core::Mode::from_legacy)
        .unwrap_or(item.meta.mode);
    core_mode.into()
}

/// Optional geofence-id passthrough (`geofence_id`/`__geofence_id`) from
/// `meta.extra`; `None` triggers the geofence-by-name fallback.
fn route_geofence_id(item: &KojiGeometry) -> Option<u64> {
    item.meta
        .extra
        .get("geofence_id")
        .or_else(|| item.meta.extra.get("__geofence_id"))
        .and_then(|v| v.as_u64())
}

/// The stored geojson geometry Json for a route row — the reverse of
/// `to_koji_geometry`'s parse (`geo` → geojson → Json object).
fn route_geometry_json(item: &KojiGeometry) -> Json {
    let gj = geojson::Geometry::new(geojson::GeometryValue::from(&item.geometry));
    serde_json::to_value(GeoJson::Geometry(gj)).expect("geojson serializes")
}

impl Model {
    /// Map this route row to a `KojiGeometry` (the universal boundary type).
    /// Mirrors `geofence::Model::to_koji_geometry`: the geometry JSON is parsed
    /// to geo-types and the `mode` column (now the canonical 4-value `Mode`)
    /// bridges directly to `koji_core::Mode` via the `enum_bridge!` `From` impl.
    /// Routes have no `parent` hierarchy, so `parent_id`/`ancestors` stay at
    /// their defaults.
    #[allow(clippy::result_large_err)]
    pub fn to_koji_geometry(&self) -> Result<koji_core::KojiGeometry, ModelError> {
        let gj = serde_json::from_value::<geojson::Geometry>(self.geometry.clone())
            .map_err(|e| ModelError::Custom(format!("[GEOMETRY]: {e}")))?;
        let geometry = geo::Geometry::<Precision>::try_from(&gj)
            .map_err(|e| ModelError::Custom(format!("[GEOMETRY]: {e}")))?;

        // Route-only fields (no named slot in KojiMeta) ride in `extra`, which the
        // geojson serializer flattens into Feature `properties` — so the show page
        // (and any consumer) sees `geofence_id` + `description`, not just id/name/mode.
        let mut extra = serde_json::Map::new();
        extra.insert(
            "geofence_id".to_string(),
            serde_json::json!(self.geofence_id),
        );
        if let Some(description) = &self.description {
            extra.insert("description".to_string(), serde_json::json!(description));
        }

        let meta = koji_core::KojiMeta {
            id: Some(self.id),
            name: Some(self.name.clone()),
            mode: self.mode.into(),
            parent_id: None,
            ancestors: Vec::new(),
            extra,
        };
        Ok(koji_core::KojiGeometry { geometry, meta })
    }
}

pub struct Query;

impl Query {
    pub async fn paginate(
        db: &DatabaseConnection,
        args: AdminReqParsed,
    ) -> Result<PaginateResults<Vec<Json>>, DbErr> {
        let column = Column::from_str(&args.sort_by).unwrap_or(Column::Name);

        let mut paginator = Entity::find()
            .select_only()
            .column(Column::Id)
            .column(Column::Name)
            .column(Column::Mode)
            .column(Column::Points)
            .column(Column::GeofenceId)
            .column(Column::Description)
            .column(Column::CreatedAt)
            .column(Column::UpdatedAt)
            .order_by(column, parse_order(&args.order))
            .filter(Column::Name.like(format!("%{}%", args.q).as_str()));

        if let Some(geofence_id) = args.geofenceid {
            paginator = paginator.filter(Column::GeofenceId.eq(geofence_id));
        }
        if let Some(mode) = args.mode {
            paginator = paginator.filter(Column::Mode.eq(mode));
        }
        if let Some(pointsmin) = args.pointsmin {
            if let Some(pointsmax) = args.pointsmax {
                paginator = paginator.filter(Column::Points.between(pointsmin, pointsmax));
            } else {
                paginator = paginator.filter(Column::Points.gt(pointsmin));
            }
        } else if let Some(pointsmax) = args.pointsmax {
            paginator = paginator.filter(Column::Points.lt(pointsmax));
        }

        let paginator = paginator
            .into_model::<RouteNoGeometry>()
            .paginate(db, args.per_page);
        let total = paginator.num_items_and_pages().await?;

        let results: Vec<Json> = paginator
            .fetch_page(args.page)
            .await?
            .into_iter()
            .map(|model| {
                json!({
                    "id": model.id,
                    "geofence_id": model.geofence_id,
                    "name": model.name,
                    "description": model.description,
                    "points": model.points,
                    "mode": model.mode,
                })
            })
            .collect();

        Ok(PaginateResults {
            results,
            total: total.number_of_items,
            has_prev: args.page > 0,
            has_next: args.page + 1 < total.number_of_pages,
        })
    }

    /// Returns all Geofence models in the db
    pub async fn get_all(db: &DatabaseConnection) -> Result<Vec<Model>, DbErr> {
        Entity::find().all(db).await
    }

    pub async fn get_json_cache(db: &DatabaseConnection) -> Result<Vec<sea_orm::JsonValue>, DbErr> {
        let results = Query::get_all_no_fences(db)
            .await?
            .into_iter()
            .map(|record| {
                let mut json = json!(record);
                json["geo_type"] = Json::String("MultiPoint".to_string());
                json
            })
            .collect();
        Ok(results)
    }

    /// Returns all Geofence models in the db without their features
    pub async fn get_all_no_fences(db: &DatabaseConnection) -> Result<Vec<RouteNoGeometry>, DbErr> {
        Entity::find()
            .select_only()
            .column(Column::Id)
            .column(Column::GeofenceId)
            .column(Column::Name)
            .column(Column::Description)
            .column(Column::Mode)
            .column(Column::Points)
            .column(Column::CreatedAt)
            .column(Column::UpdatedAt)
            .order_by(Column::Name, Order::Asc)
            .into_model::<RouteNoGeometry>()
            .all(db)
            .await
    }

    /// Creates a new Geofence model, only used from admin panel when creating a single geofence.
    /// Does not try to remove internal props since they do not exist yet
    pub async fn create(db: &DatabaseConnection, incoming: Model) -> Result<Model, DbErr> {
        let new_fence = serde_json::from_value::<geojson::Geometry>(incoming.geometry);
        match new_fence {
            Ok(new_feature) => {
                let value = serde_json::to_value(GeoJson::Geometry(new_feature))
                    .expect("geojson serializes");
                ActiveModel {
                    name: Set(incoming.name.to_owned()),
                    geofence_id: Set(incoming.geofence_id),
                    geometry: Set(value),
                    mode: Set(incoming.mode),
                    description: Set(incoming.description),
                    created_at: Set(Utc::now()),
                    updated_at: Set(Utc::now()),
                    ..Default::default()
                }
                .insert(db)
                .await
            }
            Err(err) => Err(DbErr::Custom(format!(
                "New area did not have valid geometry {:?}",
                err
            ))),
        }
    }

    pub async fn get_one(db: &DatabaseConnection, id: String) -> Result<Model, ModelError> {
        let record = match id.parse::<u32>() {
            Ok(id) => Entity::find_by_id(id).one(db).await?,
            Err(_) => Entity::find().filter(Column::Name.eq(id)).one(db).await?,
        };
        if let Some(record) = record {
            Ok(record)
        } else {
            Err(ModelError::Route("Does not exist".to_string()))
        }
    }

    pub async fn get_one_json(db: &DatabaseConnection, id: String) -> Result<Json, ModelError> {
        match Query::get_one(db, id).await {
            Ok(record) => Ok(json!(record)),
            Err(err) => Err(err),
        }
    }

    pub async fn update(
        db: &DatabaseConnection,
        id: u32,
        new_model: Model,
    ) -> Result<Model, DbErr> {
        let old_model: Option<Model> = Entity::find_by_id(id).one(db).await?;
        let new_geometry = serde_json::from_value::<geojson::Geometry>(new_model.geometry);
        if let Ok(new_geometry) = new_geometry {
            let value =
                serde_json::to_value(GeoJson::Geometry(new_geometry)).expect("geojson serializes");

            let mut old_model: ActiveModel = old_model.unwrap().into();
            old_model.name = Set(new_model.name.to_owned());
            old_model.description = Set(new_model.description.to_owned());
            old_model.geofence_id = Set(new_model.geofence_id);
            old_model.geometry = Set(value);
            old_model.mode = Set(new_model.mode);
            old_model.updated_at = Set(Utc::now());
            old_model.update(db).await
        } else {
            Err(DbErr::Custom("New geometry was not valid".to_string()))
        }
    }

    pub async fn delete(db: &DatabaseConnection, id: u32) -> Result<DeleteResult, DbErr> {
        let record = Entity::delete_by_id(id).exec(db).await?;
        Ok(record)
    }

    /// Fetch all route rows (ordered by name) and map each `Model` to a
    /// `KojiGeometry`, collecting into a `KojiGeometryCollection`. Returns
    /// `ModelError` to match `route::Model::to_koji_geometry`. The geojson
    /// property naming an `internal` flag would control is irrelevant for the
    /// self-describing `KojiMeta`, so it is not needed here.
    #[allow(clippy::result_large_err)]
    pub async fn as_koji_collection(
        conn: &DatabaseConnection,
    ) -> Result<koji_core::KojiGeometryCollection, ModelError> {
        let items = Entity::find()
            .order_by(Column::Name, Order::Asc)
            .all(conn)
            .await?;
        items
            .iter()
            .map(|item| item.to_koji_geometry())
            .collect::<Result<koji_core::KojiGeometryCollection, ModelError>>()
    }

    /// Fetch one route row by id and map it via `to_koji_geometry`. Returns
    /// `ModelError` to match the sibling Koji read methods.
    #[allow(clippy::result_large_err)]
    pub async fn get_one_koji(
        db: &DatabaseConnection,
        id: String,
    ) -> Result<koji_core::KojiGeometry, ModelError> {
        let record = Query::get_one(db, id).await?;
        record.to_koji_geometry()
    }

    pub async fn upsert<C: ConnectionTrait>(
        db: &C,
        id: u32,
        json: Json,
    ) -> Result<Model, ModelError> {
        let old_model = Entity::find_by_id(id).one(db).await?;
        let mut new_model = json.to_route()?;

        let model = if let Some(old_model) = old_model {
            new_model.id = Set(old_model.id);
            new_model.update(db).await?
        } else {
            new_model.insert(db).await?
        };
        Ok(model)
    }

    pub async fn upsert_json_return<C: ConnectionTrait>(
        db: &C,
        id: u32,
        json: Json,
    ) -> Result<Json, ModelError> {
        let result = Query::upsert(db, id, json).await?;
        Ok(json!(result))
    }

    /// Resolve the geofence id for a route item. Prefer the explicit
    /// `geofence_id`/`__geofence_id` passthrough in `meta.extra`; otherwise fall
    /// back to the geofence whose name matches the route name (the legacy
    /// behavior of the deleted `upsert_feature`).
    async fn resolve_geofence_id(
        conn: &DatabaseConnection,
        item: &KojiGeometry,
        name: &str,
    ) -> Result<Option<u32>, DbErr> {
        if let Some(fence_id) = route_geofence_id(item) {
            return Ok(Some(fence_id as u32));
        }
        let geofence = geofence::Entity::find()
            .filter(geofence::Column::Name.eq(Value::String(Some(Box::new(name.to_string())))))
            .one(conn)
            .await?;
        Ok(geofence.map(|g| g.id))
    }

    /// Persist one route directly from a `KojiGeometry` (no geojson `Feature`
    /// round-trip). `existing` keys `name_mode` to the current row so a matching
    /// route is updated rather than re-inserted. Returns whether the row was an
    /// update (`true`) or an insert (`false`).
    async fn upsert_koji_item(
        conn: &DatabaseConnection,
        item: &KojiGeometry,
        existing: &HashMap<String, RouteNoGeometry>,
    ) -> Result<bool, DbErr> {
        let Some(name) = route_name(item) else {
            let error = format!(
                "[ROUTE_SAVE] name property not found for {:?}",
                item.meta.id
            );
            log::warn!("{error}");
            return Err(DbErr::Custom(error));
        };
        let mode = route_mode(item);
        let Some(fence_id) = Query::resolve_geofence_id(conn, item, &name).await? else {
            let error = format!("[ROUTE_SAVE] could not resolve geofence_id for {name}");
            log::warn!("{error}");
            return Err(DbErr::Custom(error));
        };
        let geometry = route_geometry_json(item);

        let is_update = existing.get(&format!("{}_{}", name, mode.to_value()));
        let mut active_model = if let Some(entry) = is_update {
            Entity::find_by_id(entry.id)
                .one(conn)
                .await?
                .unwrap()
                .into()
        } else {
            ActiveModel {
                ..Default::default()
            }
        };
        active_model.geofence_id = Set(fence_id);
        active_model.geometry = Set(geometry);
        active_model.mode = Set(mode);
        active_model.updated_at = Set(Utc::now());
        if is_update.is_some() {
            active_model.update(conn).await?;
            Ok(true)
        } else {
            active_model.name = Set(name);
            active_model.created_at = Set(Utc::now());
            active_model.insert(conn).await?;
            Ok(false)
        }
    }

    pub async fn upsert_from_geometry(
        conn: &DatabaseConnection,
        area: &KojiGeometryCollection,
    ) -> Result<(usize, usize), DbErr> {
        let existing: HashMap<String, RouteNoGeometry> = Query::get_all_no_fences(conn)
            .await?
            .into_iter()
            .map(|model| (format!("{}_{}", model.name, model.mode.to_value()), model))
            .collect();

        let mut inserts = 0;
        let mut updates = 0;

        for item in &area.items {
            // Persist directly from the Koji item — name/mode/geofence_id come
            // from `KojiMeta` (with `__`-prefixed `extra` passthrough for legacy
            // producers); no geojson `Feature` round-trip.
            if Query::upsert_koji_item(conn, item, &existing).await? {
                updates += 1;
            } else {
                inserts += 1;
            }
        }

        Ok((inserts, updates))
    }

    pub async fn search(db: &DatabaseConnection, search: String) -> Result<Vec<Json>, DbErr> {
        Entity::find()
            .filter(Column::Name.like(format!("%{}%", search).as_str()))
            .into_json()
            .all(db)
            .await
    }
}

#[cfg(test)]
mod to_koji_tests {
    // `Mode` here is the domain `koji_core::Mode` (what `KojiMeta`/`meta.mode`
    // use); the storage enum is aliased `DbMode` for the `Model` fixtures and the
    // `route_mode` helper (which returns the sea-orm `Mode`).
    use super::{Mode as DbMode, *};
    use koji_core::{KojiMeta, Mode};

    #[cfg(test)]
    fn test_model_defaults() -> Model {
        use chrono::Utc;
        Model {
            id: 0,
            geofence_id: 0,
            name: String::new(),
            description: None,
            mode: DbMode::Unset,
            geometry: serde_json::json!(null),
            points: 0,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        }
    }

    #[test]
    fn route_model_to_koji_geometry_maps_mode_and_geometry() {
        let model = Model {
            id: 42,
            geofence_id: 7,
            name: "Patrol".to_string(),
            geometry: serde_json::json!({
                "type": "LineString",
                "coordinates": [[1.0, 2.0], [3.0, 4.0]]
            }),
            mode: DbMode::Fort,
            ..test_model_defaults()
        };

        let kg = model.to_koji_geometry().unwrap();
        assert!(matches!(kg.geometry, geo::Geometry::LineString(_)));
        assert_eq!(kg.meta.mode, Mode::Fort); // mode bridges Model.mode -> koji_core::Mode
        assert_eq!(kg.meta.name.as_deref(), Some("Patrol"));
        assert_eq!(kg.meta.id, Some(42));
        // Routes have no parent hierarchy.
        assert_eq!(kg.meta.parent_id, None);
        assert!(kg.meta.ancestors.is_empty());
    }

    /// Build a route `KojiGeometry` the way the v2 Koji-native path would: typed
    /// `meta.name`/`meta.mode`, a MultiPoint geometry, an explicit `geofence_id`
    /// passthrough in `extra`.
    fn koji_route_item() -> KojiGeometry {
        use geo::{Geometry, MultiPoint, Point};
        let mut extra = serde_json::Map::new();
        extra.insert("geofence_id".to_string(), serde_json::json!(7));
        KojiGeometry {
            geometry: Geometry::MultiPoint(MultiPoint::from(vec![
                Point::new(2.0, 1.0),
                Point::new(4.0, 3.0),
            ])),
            meta: KojiMeta {
                name: Some("r1".to_string()),
                mode: Mode::Fort,
                extra,
                ..Default::default()
            },
        }
    }

    #[test]
    fn route_persistence_inputs_from_typed_meta() {
        let item = koji_route_item();
        // name comes straight from the typed field.
        assert_eq!(route_name(&item).as_deref(), Some("r1"));
        // Fort with no original `__mode` string bridges the typed meta.mode.
        assert_eq!(route_mode(&item), DbMode::Fort);
        // geofence_id passthrough is read from `extra`.
        assert_eq!(route_geofence_id(&item), Some(7));
        // geometry serializes back to a MultiPoint geojson object.
        let gj = route_geometry_json(&item);
        assert_eq!(gj["type"], "MultiPoint");
        assert_eq!(
            gj["coordinates"],
            serde_json::json!([[2.0, 1.0], [4.0, 3.0]])
        );
    }

    #[test]
    fn route_persistence_inputs_honor_legacy_underscore_props() {
        // The legacy producer path (bootstrap / v1 calculate) leaves the original
        // values under `__name`/`__mode`/`__geofence_id` in `extra`, with the
        // typed fields at their defaults. Those must still win.
        use geo::{Geometry, MultiPoint, Point};
        let mut extra = serde_json::Map::new();
        extra.insert("__name".to_string(), serde_json::json!("legacy_route"));
        extra.insert("__mode".to_string(), serde_json::json!("circle_pokemon"));
        extra.insert("__geofence_id".to_string(), serde_json::json!(99));
        let item = KojiGeometry {
            geometry: Geometry::MultiPoint(MultiPoint::from(vec![Point::new(2.0, 1.0)])),
            meta: KojiMeta {
                extra,
                ..Default::default()
            },
        };
        assert_eq!(route_name(&item).as_deref(), Some("legacy_route"));
        // The legacy 12-value `__mode` string collapses to the canonical Mode.
        assert_eq!(route_mode(&item), DbMode::Pokemon);
        assert_eq!(route_geofence_id(&item), Some(99));
    }

    #[test]
    fn route_mode_default_maps_to_unset() {
        use geo::{Geometry, Point};
        let item = KojiGeometry {
            geometry: Geometry::Point(Point::new(0.0, 0.0)),
            meta: KojiMeta::default(),
        };
        assert_eq!(route_mode(&item), DbMode::Unset);
        assert_eq!(route_name(&item), None);
        assert_eq!(route_geofence_id(&item), None);
    }

    fn route_row_for_feature() -> Model {
        Model {
            id: 3,
            geofence_id: 88,
            name: "patrol".to_string(),
            geometry: serde_json::json!({
                "type": "MultiPoint",
                "coordinates": [[1.0, 2.0], [3.0, 4.0]]
            }),
            mode: DbMode::Pokemon, // canonical 4-value mode
            ..test_model_defaults()
        }
    }

    /// S8 route-publish payload golden: the `RouteUpdated.route` `SingleVec` the
    /// publish handler emits. The producer is `get_one_koji(...)` wrapped in a
    /// one-item `KojiGeometryCollection`, run through the Phase 1B inherent
    /// `to_single_vec` (matrix-free). (`get_one_koji` only adds a DB fetch around
    /// `to_koji_geometry`, so testing the `Model` conversion pins the producer
    /// without a DB.) The golden `[[2,1],[4,3]]` was captured from the matrix
    /// oracle (`to_feature(false).to_single_vec()`) at the time of the S5d-1 swap,
    /// where the two paths were asserted byte-identical; it now stands as a
    /// permanent regression guard after the oracle dies.
    #[test]
    fn route_publish_single_vec_golden() {
        let model = route_row_for_feature();

        // Producer: Model -> to_koji_geometry -> one-item collection -> to_single_vec.
        let kg = model.to_koji_geometry().unwrap();
        let single_vec = KojiGeometryCollection::new(vec![kg]).to_single_vec();

        // The stored MultiPoint [[1,2],[3,4]] (lon,lat) becomes [lat, lon] points,
        // in order — the captured matrix golden.
        assert_eq!(
            single_vec,
            vec![[2.0, 1.0], [4.0, 3.0]],
            "route publish SingleVec diverged from the captured matrix golden"
        );
    }

}
