//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

use chrono::Utc;
use serde::Serialize;

pub mod prelude;

pub mod area;
pub mod device;
pub mod geofence;
pub mod geofence_project;
pub mod gym;
pub mod instance;
pub mod pokestop;
pub mod project;
pub mod sea_orm_active_enums;
pub mod spawnpoint;

#[derive(Debug, Serialize)]
pub struct PaginateResults<T> {
    results: Vec<T>,
    total: usize,
    has_next: bool,
    has_prev: bool,
}
