//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

extern crate futures;

use chrono::Utc;
use sea_orm::{DeleteResult, FromQueryResult, Order, QueryOrder, QuerySelect, Set};
use serde::{Deserialize, Serialize};

use futures::future;

pub mod prelude;

pub mod area;
pub mod device;
pub mod geofence;
pub mod geofence_project;
pub mod gym;
pub mod instance;
pub mod pokestop;
pub mod project;
pub mod sea_orm_active_enums;
pub mod spawnpoint;

#[derive(Debug, Serialize)]
pub struct PaginateResults<T> {
    pub results: Vec<(T, Vec<NameId>)>,
    total: usize,
    has_next: bool,
    has_prev: bool,
}

#[derive(Debug, Serialize, FromQueryResult)]
pub struct NameId {
    id: u32,
    name: String,
}
