//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

use sea_orm::{entity::prelude::*, strum::Display};
use serde::{Deserialize, Serialize};

#[derive(
    Debug, Display, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Deserialize, Serialize,
)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "type")]
pub enum Type {
    #[sea_orm(string_value = "circle_pokemon")]
    CirclePokemon,
    #[sea_orm(string_value = "circle_smart_pokemon")]
    CircleSmartPokemon,
    #[sea_orm(string_value = "circle_raid")]
    CircleRaid,
    #[sea_orm(string_value = "circle_smart_raid")]
    CircleSmartRaid,
    #[sea_orm(string_value = "auto_quest")]
    AutoQuest,
    // This is added manually, re-add it if you run the CLI command
    #[sea_orm(string_value = "manual_quest")]
    ManualQuest,
    #[sea_orm(string_value = "pokemon_iv")]
    PokemonIv,
    #[sea_orm(string_value = "leveling")]
    Leveling,
    #[sea_orm(string_value = "auto_pokemon")]
    AutoPokemon,
    #[sea_orm(string_value = "auto_tth")]
    AutoTth,
}
