use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Queryable)]
pub struct Spawnpoint {
    pub id: u64,
    pub lat: f64,
    pub lon: f64,
    pub updated: u32,
    pub last_seen: u32,
    pub despawn_sec: Option<u16>,
}

#[derive(Debug, Serialize, Deserialize, Queryable)]
pub struct Pokestop {
    pub id: String,
    pub lat: f64,
    pub lon: f64,
    pub name: Option<String>,
    pub url: Option<String>,
    pub last_modified_timestamp: Option<u32>,
    pub updated: u32,
    pub enabled: Option<u8>,
    pub cell_id: Option<u64>,
    pub deleted: u8,
    pub first_seen_timestamp: u32,
    pub sponsor_id: Option<u16>,
    pub partner_id: Option<String>,
    pub ar_scan_eligible: Option<u8>,
}

#[derive(Debug, Serialize, Deserialize, Queryable)]
pub struct Gym {
    pub id: String,
    pub lat: f64,
    pub lon: f64,
    pub name: Option<String>,
    pub url: Option<String>,
    pub last_modified_timestamp: Option<u32>,
    pub updated: u32,
    pub enabled: Option<u8>,
    pub ex_raid_eligible: Option<u8>,
    pub cell_id: Option<u64>,
    pub deleted: u8,
    pub first_seen_timestamp: u32,
    pub sponsor_id: Option<u16>,
    pub ar_scan_eligible: Option<u8>,
    // pub raid_end_timestamp: Option<u32>,
    // pub raid_spawn_timestamp: Option<u32>,
    // pub raid_battle_timestamp: Option<u32>,
    // pub raid_pokemon_id: Option<u16>,
    // pub guarding_pokemon_id: Option<u16>,
    // pub available_slots: Option<u16>,
    // pub availble_slots: Option<u16>,
    // pub team_id: Option<u8>,
    // pub raid_level: Option<u8>,
    // pub enabled: Option<u8>,
    // pub in_battle: Option<u8>,
    // pub raid_pokemon_move_1: Option<u16>,
    // pub raid_pokemon_move_2: Option<u16>,
    // pub raid_pokemon_form: Option<u16>,
    // pub raid_pokemon_cp: Option<u32>,
    // pub raid_is_exclusive: Option<u8>,
    // pub total_cp: Option<u32>,
    // pub raid_pokemon_gender: Option<u8>,
    // pub raid_pokemon_costume: Option<u16>,
    // pub raid_pokemon_evolution: Option<u8>,
    // pub power_up_level: Option<u16>,
    // pub power_up_points: Option<u32>,
    // pub power_up_end_timestamp: Option<u32>,
}
