[package]
name = "algorithms"
version = "0.5.0"
edition = "2021"
publish = false

[lib]
name = "algorithms"
path = "src/lib.rs"

[dependencies]
geo = "0.24.0"
geohash = "0.12.0"
geojson = "0.24.0"
log = "0.4.17"
map_3d = "0.1.5"
model = { path = "../model" }
rand = "0.8.5"
rstar = "0.10.0"
s2 = "0.0.12"
shuffle = "0.1.7"
# vrp-pragmatic = "1.18.3"
