[package]
name = "algorithms"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "algorithms"
path = "src/lib.rs"

[dependencies]
geo = "0.22.1"
geohash = "0.12.0"
geojson = "0.24.0"
map_3d = "0.1.5"
model = { path = "../model" }
num-traits = "0.2.15"
rstar = "0.9.3"
sea-orm = { version = "0.9.3", features = [
  "sqlx-mysql",
  "runtime-actix-native-tls",
  "macros",
] }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0"
serde_with = "2.1.0"
time = "0.3.16"
travelling_salesman = "1.1.22"
# vrp-pragmatic = "1.18.3"
