//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

use geojson::FeatureCollection;
use koji_core::Precision;
use koji_core::SpawnpointTth;
use sea_orm::entity::prelude::*;
use sea_orm::{DbBackend, QueryFilter, QuerySelect, Statement};
use serde::{Deserialize, Serialize};

use crate::normalize::{spawnpoint, spawnpoint_filtered};
use crate::rows::{GenericData, Spawnpoint, Total};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "spawnpoint")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: u64,
    pub lat: Precision,
    pub lon: Precision,
    pub updated: u32,
    pub last_seen: u32,
    pub despawn_sec: Option<u16>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

pub struct Query;

impl Query {
    pub async fn all(
        conn: &DatabaseConnection,
        last_seen: u32,
        tth: SpawnpointTth,
    ) -> Result<Vec<GenericData>, DbErr> {
        let items = Entity::find()
            .select_only()
            .column(Column::Lat)
            .column(Column::Lon)
            .column(Column::DespawnSec)
            .limit(2_000_000)
            .filter(Column::LastSeen.gt(last_seen))
            .filter(match tth {
                SpawnpointTth::All => Column::Id.is_not_null(),
                SpawnpointTth::Known => Column::DespawnSec.is_not_null(),
                SpawnpointTth::Unknown => Column::DespawnSec.is_null(),
            })
            .into_model::<Spawnpoint>()
            .all(conn)
            .await?;
        Ok(spawnpoint(items))
    }

    pub async fn bound(
        conn: &DatabaseConnection,
        payload: &koji_core::BoundsArg,
    ) -> Result<Vec<GenericData>, DbErr> {
        let items = Entity::find()
            .select_only()
            .column(Column::Lat)
            .column(Column::Lon)
            .column(Column::DespawnSec)
            .filter(Column::Lat.between(payload.bbox.min_lat, payload.bbox.max_lat))
            .filter(Column::Lon.between(payload.bbox.min_lon, payload.bbox.max_lon))
            .filter(Column::LastSeen.gt(payload.last_seen.unwrap_or(0)))
            .filter(match payload.tth.as_ref().unwrap_or(&SpawnpointTth::All) {
                SpawnpointTth::All => Column::Id.is_not_null(),
                SpawnpointTth::Known => Column::DespawnSec.is_not_null(),
                SpawnpointTth::Unknown => Column::DespawnSec.is_null(),
            })
            .limit(2_000_000)
            .into_model::<Spawnpoint>()
            .all(conn)
            .await?;
        Ok(spawnpoint(items))
    }

    async fn query_area(
        conn: &DatabaseConnection,
        area: &FeatureCollection,
        last_seen: u32,
        tth: SpawnpointTth,
    ) -> Result<Vec<Spawnpoint>, DbErr> {
        Entity::find()
            .from_raw_sql(Statement::from_sql_and_values(
                DbBackend::MySql,
                format!(
                    "SELECT lat, lon, despawn_sec FROM spawnpoint WHERE last_seen > {} {} AND ({})",
                    last_seen,
                    match tth {
                        SpawnpointTth::All => "".to_string(),
                        SpawnpointTth::Known => "AND despawn_sec IS NOT NULL".to_string(),
                        SpawnpointTth::Unknown => "AND despawn_sec IS NULL".to_string(),
                    },
                    crate::sql_raw_bbox(area)
                )
                .as_str(),
                vec![],
            ))
            .into_model::<Spawnpoint>()
            .all(conn)
            .await
    }

    pub async fn area(
        conn: &DatabaseConnection,
        area: &FeatureCollection,
        last_seen: u32,
        tth: SpawnpointTth,
    ) -> Result<Vec<GenericData>, DbErr> {
        let items = Self::query_area(conn, area, last_seen, tth).await?;
        Ok(spawnpoint_filtered(items, area))
    }

    pub async fn stats(
        conn: &DatabaseConnection,
        area: &FeatureCollection,
        last_seen: u32,
        tth: SpawnpointTth,
    ) -> Result<Total, DbErr> {
        let items = Self::query_area(conn, area, last_seen, tth).await?;
        let total = crate::count_in_area(&items, area);
        Ok(Total { total })
    }
}
