//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

use koji_core::Precision;
use std::time::{SystemTime, UNIX_EPOCH};

use geojson::FeatureCollection;
use sea_orm::entity::prelude::*;
use sea_orm::{DbBackend, Statement};
use serde::{Deserialize, Serialize};

use crate::normalize::fort_filtered;
use crate::rows::{GenericData, LatLonRow, Total};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "station")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub lat: Precision,
    pub lon: Precision,
    pub name: String,
    pub cell_id: u64,
    pub start_time: u32,
    pub end_time: u32,
    pub cooldown_complete: u32,
    pub is_battle_available: u8,
    pub is_inactive: u8,
    pub battle_level: Option<u8>,
    pub battle_start: Option<u32>,
    pub battle_end: Option<u32>,
    pub battle_pokemon_id: Option<u16>,
    pub battle_pokemon_form: Option<u16>,
    pub battle_pokemon_costume: Option<u16>,
    pub battle_pokemon_gender: Option<u8>,
    pub battle_pokemon_alignment: Option<u16>,
    pub battle_pokemon_bread_mode: Option<u16>,
    pub battle_pokemon_move_1: Option<u16>,
    pub battle_pokemon_move_2: Option<u16>,
    pub updated: u32,
    pub total_stationed_pokemon: Option<u16>,
    pub total_stationed_gmax: Option<u16>,
    #[sea_orm(column_type = "Text", nullable)]
    pub stationed_pokemon: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

fn now_secs() -> u32 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_secs() as u32
}

pub struct Query;

impl Query {
    /// The shared raw-SQL fetch for active stations in `area` — `area` and
    /// `stats` previously duplicated this verbatim (mirrors spawnpoint.rs's
    /// `query_area` helper).
    async fn query_area(
        conn: &DatabaseConnection,
        area: &FeatureCollection,
        last_seen: u32,
    ) -> Result<Vec<LatLonRow>, DbErr> {
        let now = now_secs();
        Entity::find()
            .from_raw_sql(Statement::from_sql_and_values(
                DbBackend::MySql,
                format!("SELECT lat, lon FROM station WHERE is_inactive = 0 AND updated > {} AND end_time > {} AND ({})", last_seen, now, crate::sql_raw_bbox(area)).as_str(),
                vec![],
            ))
            .into_model::<LatLonRow>()
            .all(conn)
            .await
    }

    pub async fn area(
        conn: &DatabaseConnection,
        area: &FeatureCollection,
        last_seen: u32,
    ) -> Result<Vec<GenericData>, DbErr> {
        let items = Self::query_area(conn, area, last_seen).await?;
        Ok(fort_filtered(items, area, "s"))
    }

    pub async fn stats(
        conn: &DatabaseConnection,
        area: &FeatureCollection,
        last_seen: u32,
    ) -> Result<Total, DbErr> {
        let items = Self::query_area(conn, area, last_seen).await?;
        let total = crate::count_in_area(&items, area);
        Ok(Total { total })
    }
}
