[package]
name = "koji-golbat"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "koji_golbat"
path = "src/lib.rs"

[dependencies]
koji-core = { path = "../koji-core" }
macros = { workspace = true }
geo = { workspace = true }
geojson = { workspace = true }
log = { workspace = true }
sea-orm = { version = "1.1.16", features = [
  "sqlx-mysql",
  "runtime-actix-native-tls",
  "macros",
] }
serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
