//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "pokestop")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub lat: f64,
    pub lon: f64,
    pub name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub url: Option<String>,
    pub lure_expire_timestamp: Option<u32>,
    pub last_modified_timestamp: Option<u32>,
    pub updated: u32,
    pub enabled: Option<u8>,
    pub quest_type: Option<u32>,
    pub quest_timestamp: Option<u32>,
    pub quest_target: Option<u16>,
    #[sea_orm(column_type = "Text", nullable)]
    pub quest_conditions: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub quest_rewards: Option<String>,
    pub quest_template: Option<String>,
    pub quest_title: Option<String>,
    pub quest_reward_type: Option<i16>,
    pub quest_item_id: Option<i16>,
    pub quest_reward_amount: Option<i16>,
    pub cell_id: Option<u64>,
    pub deleted: u8,
    pub lure_id: Option<i16>,
    pub first_seen_timestamp: u32,
    pub sponsor_id: Option<u16>,
    pub partner_id: Option<String>,
    pub quest_pokemon_id: Option<i16>,
    pub ar_scan_eligible: Option<u8>,
    pub power_up_level: Option<u16>,
    pub power_up_points: Option<u32>,
    pub power_up_end_timestamp: Option<u32>,
    pub alternative_quest_type: Option<u32>,
    pub alternative_quest_timestamp: Option<u32>,
    pub alternative_quest_target: Option<u16>,
    #[sea_orm(column_type = "Text", nullable)]
    pub alternative_quest_conditions: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub alternative_quest_rewards: Option<String>,
    pub alternative_quest_template: Option<String>,
    pub alternative_quest_title: Option<String>,
    pub alternative_quest_pokemon_id: Option<i16>,
    pub alternative_quest_reward_type: Option<i16>,
    pub alternative_quest_item_id: Option<i16>,
    pub alternative_quest_reward_amount: Option<i16>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
