//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

pub use super::device::Entity as Device;
pub use super::gym::Entity as Gym;
pub use super::instance::Entity as Instance;
pub use super::pokestop::Entity as Pokestop;
pub use super::spawnpoint::Entity as Spawnpoint;
