//! Boundary mapping between the sea-orm generated enums (`db::Type`,
//! `db::Category`) and the pure domain enums in koji-core, generated by
//! `koji_core::enum_bridge!`. Keeps sea-orm confined to the db layer.

koji_core::enum_bridge!(
    crate::db::sea_orm_active_enums::Type,
    koji_core::FenceType,
    [
        CirclePokemon,
        CircleSmartPokemon,
        CircleRaid,
        CircleSmartRaid,
        AutoQuest,
        CircleQuest,
        CircleStation,
        PokemonIv,
        Leveling,
        AutoPokemon,
        AutoTth,
        Unset,
    ]
);

koji_core::enum_bridge!(
    crate::db::sea_orm_active_enums::Category,
    koji_core::Category,
    [Boolean, String, Number, Object, Array, Database, Color]
);
