//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

use crate::error::ModelError;

use super::*;

use sea_orm::{
    DbBackend, DeleteResult, DeriveEntityModel, FromQueryResult, Order, QueryOrder, QuerySelect,
    Set, Statement, prelude::DateTimeUtc, sea_query::Expr,
};

pub mod area;
mod enum_bridge;
pub mod geofence;
pub mod geofence_project;
pub mod geofence_property;
pub mod gym;
pub mod instance;
pub mod pokestop;
pub mod prelude;
pub mod project;
pub mod property;
pub mod route;
pub mod sea_orm_active_enums;
pub mod spawnpoint;
pub mod station;
pub mod tile_server;

/// Query-row for `SELECT lat, lon` from scanner tables. The pure geometry
/// `PointStruct` lives in koji-core (no sea-orm); this row carries the
/// `FromQueryResult` derive and converts into it.
#[derive(Debug, FromQueryResult)]
pub struct LatLonRow {
    pub lat: f64,
    pub lon: f64,
}

impl From<LatLonRow> for koji_core::PointStruct {
    fn from(r: LatLonRow) -> Self {
        koji_core::PointStruct {
            lat: r.lat,
            lon: r.lon,
        }
    }
}

trait ToFeatureFromModel {
    fn to_feature(self, internal: bool) -> Result<Feature, ModelError>;
}

#[derive(Debug, Serialize, FromQueryResult)]
pub struct NameId {
    id: u32,
    name: String,
}

#[derive(FromQueryResult)]
pub struct NameType {
    pub name: String,
    pub instance_type: self::sea_orm_active_enums::Type,
}

#[derive(Debug, Clone, FromQueryResult, Serialize, Deserialize)]
pub struct NameTypeId {
    pub id: u32,
    pub name: String,
    pub mode: self::sea_orm_active_enums::Type,
    pub geo_type: Option<String>,
}

#[derive(Debug, FromQueryResult)]
pub struct AreaRef {
    pub id: u32,
    pub name: String,
    pub has_geofence: bool,
    pub has_pokemon: bool,
    pub has_quest: bool,
    pub has_fort: bool,
}

#[derive(Debug, FromQueryResult, Serialize, Deserialize, Clone)]
pub struct Total {
    pub total: i32,
}

#[derive(Debug, Serialize)]
pub struct PaginateResults<T> {
    results: T,
    total: u64,
    has_next: bool,
    has_prev: bool,
}

impl Default for PaginateResults<()> {
    fn default() -> Self {
        PaginateResults {
            results: (),
            total: 0,
            has_next: false,
            has_prev: false,
        }
    }
}

#[derive(Debug, Clone, FromQueryResult)]
pub struct Spawnpoint {
    pub lat: f64,
    pub lon: f64,
    pub despawn_sec: Option<u16>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(untagged)]
pub enum RdmInstanceArea {
    Leveling(koji_core::PointStruct),
    Single(koji_core::SingleStruct),
    Multi(koji_core::MultiStruct),
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct RdmInstance {
    pub area: RdmInstanceArea,
    pub radius: Option<u32>,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct GenericData {
    pub i: String,
    pub p: [f64; 2],
}

impl GenericData {
    pub fn new(i: String, lat: f64, lon: f64) -> Self {
        GenericData { i, p: [lat, lon] }
    }
}

impl koji_core::ToPointArray for GenericData {
    fn to_point_array(self) -> koji_core::PointArray {
        self.p
    }
}
impl koji_core::ToPointStruct for GenericData {
    fn to_struct(self) -> koji_core::PointStruct {
        koji_core::PointStruct {
            lat: self.p[0],
            lon: self.p[1],
        }
    }
}

pub trait GenericDataToVec {
    fn to_single_vec(self) -> koji_core::SingleVec;
}

impl GenericDataToVec for Vec<GenericData> {
    fn to_single_vec(self) -> koji_core::SingleVec {
        self.into_iter()
            .map(|p| koji_core::ToPointArray::to_point_array(p))
            .collect()
    }
}

#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(untagged)]
pub enum InstanceParsing {
    Feature(Feature),
    Rdm(RdmInstance),
}

pub struct InsertsUpdates<T> {
    to_insert: Vec<T>,
    updates: usize,
    inserts: usize,
}

pub trait VecToJson {
    fn to_json(self) -> Vec<serde_json::Value>;
}
