//! SeaORM Entity. Generated by sea-orm-codegen 0.10.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Deserialize, Serialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "type")]
pub enum Type {
    #[sea_orm(string_value = "circle_pokemon")]
    CirclePokemon,
    #[sea_orm(string_value = "circle_smart_pokemon")]
    CircleSmartPokemon,
    #[sea_orm(string_value = "circle_raid")]
    CircleRaid,
    #[sea_orm(string_value = "circle_smart_raid")]
    CircleSmartRaid,
    #[sea_orm(string_value = "auto_quest")]
    AutoQuest,
    // This is added manually, re-add it if you run the CLI command
    #[sea_orm(string_value = "circle_quest")]
    CircleQuest,
    #[sea_orm(string_value = "pokemon_iv")]
    PokemonIv,
    #[sea_orm(string_value = "leveling")]
    Leveling,
    #[sea_orm(string_value = "auto_pokemon")]
    AutoPokemon,
    #[sea_orm(string_value = "auto_tth")]
    AutoTth,
    // Only valid in Kōji database
    #[sea_orm(string_value = "unset")]
    Unset,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "category")]
pub enum Category {
    #[sea_orm(string_value = "boolean")]
    Boolean,
    #[sea_orm(string_value = "string")]
    String,
    #[sea_orm(string_value = "number")]
    Number,
    #[sea_orm(string_value = "object")]
    Object,
    #[sea_orm(string_value = "array")]
    Array,
    #[sea_orm(string_value = "database")]
    Database,
    #[sea_orm(string_value = "color")]
    Color,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "mode")]
pub enum FenceMode {
    #[sea_orm(string_value = "auto_quest")]
    AutoQuest,
    #[sea_orm(string_value = "auto_pokemon")]
    AutoPokemon,
    #[sea_orm(string_value = "auto_tth")]
    AutoTth,
    #[sea_orm(string_value = "pokemon_iv")]
    PokemonIv,
    #[sea_orm(string_value = "unset")]
    Unset,
}

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "mode")]
pub enum RouteMode {
    #[sea_orm(string_value = "circle_pokemon")]
    CirclePokemon,
    #[sea_orm(string_value = "circle_smart_pokemon")]
    CircleSmartPokemon,
    #[sea_orm(string_value = "circle_raid")]
    CircleRaid,
    #[sea_orm(string_value = "circle_smart_raid")]
    CircleSmartRaid,
    #[sea_orm(string_value = "circle_quest")]
    CircleQuest,
    #[sea_orm(string_value = "unset")]
    Unset,
}
