[package]
name = "koji-service"
version = "1.5.1"
edition = "2024"
publish = false

[lib]
name = "koji_service"
path = "src/lib.rs"

[dependencies]
koji-core = { path = "../koji-core" }
koji-scanner = { path = "../koji-scanner" }
koji-db = { path = "../koji-db" }
koji-plugins = { path = "../koji-plugins" }
koji-jobs = { path = "../koji-jobs" }
koji-events = { path = "../koji-events" }
koji-dragonite = { path = "../koji-dragonite" }
actix-web = "4.11.0"
actix-files = "0.6.8"
actix-session = { version = "0.11.0", features = ["cookie-session"] }
actix-web-httpauth = "0.8.2"
algorithms = { path = "../algorithms" }
async-trait = "0.1"
geo = "0.31.0"
geojson = "0.24.2"
log = "0.4.28"
migration = { path = "../migration" }
nominatim = { path = "../nominatim" }
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0.145"
thiserror = { workspace = true }
url = "2.5.7"
